/*
 * SPDX-FileCopyrightText: 2024-2025 Sony Semiconductor Solutions Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

static const PlMainDeviceInformation kDeviceInformation[] = {};

static const size_t kDeviceInformationSize =
    sizeof(kDeviceInformation) / sizeof(kDeviceInformation[0]);

static const PlMainFeatureType kFeatureTypes[] = {
    PlMainFeatureReboot
};
static const size_t kFeatureTypesSize =
    sizeof(kFeatureTypes) / sizeof(kFeatureTypes[0]);
