/*
* SPDX-FileCopyrightText: 2024-2025 Sony Semiconductor Solutions Corporation
*
* SPDX-License-Identifier: Apache-2.0
*/

#ifndef __PL_STORAGE_ID_TBL_H
#define __PL_STORAGE_ID_TBL_H

#include "pl_storage.h"

// Global Variables -----------------------------------------------------------

typedef struct {
  int access;           // file access parameter for open
  uint32_t max_size;    // limit size
  bool is_list_type;    // File or List type
} PlStorageIdTbl;

static const PlStorageIdTbl s_id_tbl[PlStorageDataMax] = {
  [PlStorageDataDpsURL]                     = {O_RDWR,   0, true},
  [PlStorageDataCommonName]                 = {O_RDWR,   0, true},
  [PlStorageDataDpsScopeID]                 = {O_RDWR,   0, true},
  [PlStorageDataProjectID]                  = {O_RDWR,   0, true},
  [PlStorageDataRegisterToken]              = {O_RDWR,   0, true},
  [PlStorageDataWiFiSSID]                   = {O_RDWR,   0, true},
  [PlStorageDataWiFiPassword]               = {O_RDWR,   0, true},
  [PlStorageDataWiFiEncryption]             = {O_RDWR,   0, true},
  [PlStorageDataIPAddress]                  = {O_RDWR,   0, true},
  [PlStorageDataSubnetMask]                 = {O_RDWR,   0, true},
  [PlStorageDataGateway]                    = {O_RDWR,   0, true},
  [PlStorageDataDNS]                        = {O_RDWR,   0, true},
  [PlStorageDataIPMethod]                   = {O_RDWR,   0, true},
  [PlStorageDataNetIfKind]                  = {O_RDWR,   0, false},
  [PlStorageDataIPv6IPAddress]              = {O_RDWR,   0, true},
  [PlStorageDataIPv6SubnetMask]             = {O_RDWR,   0, true},
  [PlStorageDataIPv6Gateway]                = {O_RDWR,   0, true},
  [PlStorageDataIPv6DNS]                    = {O_RDWR,   0, true},
  [PlStorageDataWiFiApSSID]                 = {O_RDWR,   0, true},
  [PlStorageDataWiFiApPassword]             = {O_RDWR,   0, true},
  [PlStorageDataWiFiApEncryption]           = {O_RDWR,   0, false},
  [PlStorageDataWiFiApChannel]              = {O_RDWR,   0, false},
  [PlStorageDataWiFiApIPAddress]            = {O_RDWR,   0, false},
  [PlStorageDataWiFiApSubnetMask]           = {O_RDWR,   0, false},
  [PlStorageDataWiFiApGateway]              = {O_RDWR,   0, false},
  [PlStorageDataWiFiApDNS]                  = {O_RDWR,   0, false},
  [PlStorageDataProxyURL]                   = {O_RDWR,   0, true},
  [PlStorageDataProxyPort]                  = {O_RDWR,   0, true},
  [PlStorageDataProxyUserName]              = {O_RDWR,   0, true},
  [PlStorageDataProxyPassword]              = {O_RDWR,   0, true},
  [PlStorageDataEvpHubURL]                  = {O_RDWR,   0, true},
  [PlStorageDataEvpHubPort]                 = {O_RDWR,   0, true},
  [PlStorageDataEvpIotPlatform]             = {O_RDWR,   0, true},
  [PlStorageDataPkiRootCerts]               = {O_RDONLY, 0, false},
  [PlStorageDataPkiRootCertsHash]           = {O_RDONLY, 0, true},
  [PlStorageDataEvpTls]                     = {O_RDWR,   0, true},
  [PlStorageDataDeviceManifest]             = {O_RDONLY, 0, false},
  [PlStorageDataDebugLogLevel]              = {O_RDWR,   0, true},
  [PlStorageDataEventLogLevel]              = {O_RDWR,   0, true},
  [PlStorageDataDebugLogDestination]        = {O_RDWR,   0, true},
  [PlStorageDataLogFilter]                  = {O_RDWR,   0, true},
  [PlStorageDataLogUseFlash]                = {O_RDWR,   0, false},
  [PlStorageDataStorageName]                = {O_RDWR,   0, true},
  [PlStorageDataStorageSubDirectoryPath]    = {O_RDWR,   0, true},
  [PlStorageDataDebugLogLevel2]             = {O_RDWR,   0, false},
  [PlStorageDataEventLogLevel2]             = {O_RDWR,   0, false},
  [PlStorageDataDebugLogDestination2]       = {O_RDWR,   0, false},
  [PlStorageDataLogFilter2]                 = {O_RDWR,   0, false},
  [PlStorageDataLogUseFlash2]               = {O_RDWR,   0, false},
  [PlStorageDataStorageName2]               = {O_RDWR,   0, false},
  [PlStorageDataStorageSubDirectoryPath2]   = {O_RDWR,   0, false},
  [PlStorageDataDebugLogLevel3]             = {O_RDWR,   0, false},
  [PlStorageDataEventLogLevel3]             = {O_RDWR,   0, false},
  [PlStorageDataDebugLogDestination3]       = {O_RDWR,   0, false},
  [PlStorageDataLogFilter3]                 = {O_RDWR,   0, false},
  [PlStorageDataLogUseFlash3]               = {O_RDWR,   0, false},
  [PlStorageDataStorageName3]               = {O_RDWR,   0, false},
  [PlStorageDataStorageSubDirectoryPath3]   = {O_RDWR,   0, false},
  [PlStorageDataDebugLogLevel4]             = {O_RDWR,   0, false},
  [PlStorageDataEventLogLevel4]             = {O_RDWR,   0, false},
  [PlStorageDataDebugLogDestination4]       = {O_RDWR,   0, false},
  [PlStorageDataLogFilter4]                 = {O_RDWR,   0, false},
  [PlStorageDataLogUseFlash4]               = {O_RDWR,   0, false},
  [PlStorageDataStorageName4]               = {O_RDWR,   0, false},
  [PlStorageDataStorageSubDirectoryPath4]   = {O_RDWR,   0, false},
  [PlStorageDataNTPServer]                  = {O_RDWR,   0, true},
  [PlStorageDataNTPSyncInterval]            = {O_RDWR,   0, true},
  [PlStorageDataNTPPollingTime]             = {O_RDWR,   0, true},
  [PlStorageDataSkipModeSettings]           = {O_RDWR,   0, true},
  [PlStorageDataLimitPacketTime]            = {O_RDWR,   0, true},
  [PlStorageDataLimitRTCCorrectionValue]    = {O_RDWR,   0, true},
  [PlStorageDataSanityLimit]                = {O_RDWR,   0, true},
  [PlStorageDataSlewModeSettings]           = {O_RDWR,   0, true},
  [PlStorageDataStableRTCCorrectionValue]   = {O_RDWR,   0, true},
  [PlStorageDataStableSyncNumber]           = {O_RDWR,   0, true},
  [PlStorageDataSystemError]                = {O_RDWR,   0, true},
  [PlStorageDataFactoryResetFlag]           = {O_RDWR,   0, true},
  [PlStorageDataRTCErrorDetection]          = {O_RDWR,   0, true},
  [PlStorageDataRTCPQAParameter]            = {O_RDWR,   0, true},
  [PlStorageDataBatteryInformation]         = {O_RDWR,   0, false},
  [PlStorageDataRTCNetworkInformation]      = {O_RDWR,   0, true},
  [PlStorageDataRTCConfig]                  = {O_RDWR,   0, false},
  [PlStorageDataHoursMeter]                 = {O_RDWR,   0, true},
  [PlStorageDataSAS]                        = {O_RDWR,   0, false},
  [PlStorageDataQRModeStateFlag]            = {O_RDWR,   0, true},
  [PlStorageDataInitialSettingFlag]         = {O_RDWR,   0, true},
  [PlStorageDataHWInfoText]                 = {O_RDONLY, 0, true},
  [PlStorageDataMCULoaderVersion]           = {O_RDWR,   0, true},
  [PlStorageDataSensorLoaderVersion]        = {O_RDWR,   0, true},
  [PlStorageDataMCUFWLastUpdate]            = {O_RDWR,   0, true},
  [PlStorageDataSensorLoaderLastUpdate]     = {O_RDWR,   0, true},
  [PlStorageDataSensorFWLastUpdate]         = {O_RDWR,   0, true},
  [PlStorageDataSensorAIModelFlashAddress]  = {O_RDWR,   0, true},
  [PlStorageDataSensorLoaderFlashAddress]   = {O_RDWR,   0, true},
  [PlStorageDataSensorFWFlashAddress]       = {O_RDWR,   0, true},
  [PlStorageDataAIModelParameterSlot0]      = {O_RDONLY, 0, false},
  [PlStorageDataAIModelParameterSlot1]      = {O_RDWR,   0, false},
  [PlStorageDataAIModelParameterSlot2]      = {O_RDWR,   0, false},
  [PlStorageDataAIModelParameterSlot3]      = {O_RDWR,   0, false},
  [PlStorageDataAIModelParameterSlot4]      = {O_RDWR,   0, false},
  [PlStorageDataAIModelParameterHashSlot1]  = {O_RDWR,   0, true},
  [PlStorageDataAIModelParameterHashSlot2]  = {O_RDWR,   0, true},
  [PlStorageDataAIModelParameterHashSlot3]  = {O_RDWR,   0, true},
  [PlStorageDataAIModelParameterHashSlot4]  = {O_RDWR,   0, true},
  [PlStorageDataLMTStd]                     = {O_RDONLY, 0, true},
  [PlStorageDataPreWBStd]                   = {O_RDONLY, 0, true},
  [PlStorageDataGAMMAStd]                   = {O_RDONLY, 0, false},
  [PlStorageDataLSCStd]                     = {O_RDONLY, 0, false},
  [PlStorageDataLSCRawStd]                  = {O_RDONLY, 0, false},
  [PlStorageDataDEWARPStd]                  = {O_RDONLY, 0, false},
  [PlStorageDataLMTCustom]                  = {O_RDWR,   0, true},
  [PlStorageDataPreWBCustom]                = {O_RDWR,   0, true},
  [PlStorageDataGAMMACustom]                = {O_RDWR,   0, false},
  [PlStorageDataGAMMAAutoCustom]            = {O_RDWR,   0, false},
  [PlStorageDataLSCCustom]                  = {O_RDWR,   0, false},
  [PlStorageDataLSCRawCustom]               = {O_RDWR,   0, false},
  [PlStorageDataDEWARPCustom]               = {O_RDWR,   0, false},
  [PlStorageDataAIISPAIModelParameterSlot0] = {O_RDONLY, 0, false},
  [PlStorageDataAIISPLoaderFlashAddress]    = {O_RDWR,   0, false},
  [PlStorageDataAIISPFWFlashAddress]        = {O_RDWR,   0, false},
  [PlStorageDataAIISPAIModelParameterSlot1] = {O_RDWR,   0, false},
  [PlStorageDataAIISPAIModelParameterSlot2] = {O_RDWR,   0, false},
  [PlStorageDataAIISPAIModelParameterSlot3] = {O_RDWR,   0, false},
  [PlStorageDataAIISPAIModelParameterSlot4] = {O_RDWR,   0, false},
  [PlStorageDataAIModelSlotInfo]            = {O_RDWR,   0, false},
  [PlStorageDataAIISPAIModelSlotInfo]       = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo0]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo1]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo2]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo3]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo4]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo5]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo6]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo7]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo8]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo9]           = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo10]          = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo11]          = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo12]          = {O_RDWR,   0, true},
  [PlStorageDataFwMgrBinaryInfo13]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo14]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo15]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo16]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo17]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo18]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo19]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo20]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo21]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo22]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo23]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo24]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo25]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo26]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo27]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo28]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfo29]          = {O_RDWR,   0, false},
  [PlStorageDataFwMgrBinaryInfoMcuFirmware] = {O_RDWR,   0, true},
  [PlStorageDataEsfSensorConfig]            = {O_RDWR,   0, false},
  [PlStorageDataSpiBootLoader]              = {O_RDONLY, 0, false},
  [PlStorageDataSpiBootFirmware]            = {O_RDONLY, 0, false},
  [PlStorageDataSpiBootAIModel]             = {O_RDONLY, 0, false},
  [PlStorageDataPreInstallAIModelInfo]      = {O_RDWR,   0, false},
  [PlStorageDataPreInstallAIModel]          = {O_RDWR,   0, false},
  [PlStorageDataInputTensorOnlyModel]       = {O_RDWR,   0, false},
  [PlStorageDataInputTensorOnlyParam]       = {O_RDWR,   0, false},
  [PlStorageDataExceptionFactor]            = {O_RDWR,   0, true},
  [PlStorageDataExceptionInfo]              = {O_RDWR,   0, false},
  [PlStorageDataEvpExceptionFactor]         = {O_RDWR,   0, true},
  [PlStorageDataMigrationDone]              = {O_RDWR,   0, true},
};

// ----------------------------------------------------------------------------
#endif /* __PL_STORAGE_ID_TBL_H */
