= SystemManager Function Specification
:sectnums:
:sectnumlevels: 3
:chapter-label:
:revnumber: 0.1.11
:toc:
:toc-title: Table of Contents
:toclevels: 3
:lang: en
:xrefstyle: short
:figure-caption: Figure
:table-caption: Table
:section-refsig:
:experimental:
ifdef::env-github[:mermaid_block: source,mermaid,subs="attributes"]
ifndef::env-github[:mermaid_block: mermaid,subs="attributes"]
ifdef::env-github,env-vscode[:mermaid_break: break]
ifndef::env-github,env-vscode[:mermaid_break: opt]
ifdef::env-github,env-vscode[:mermaid_critical: critical]
ifndef::env-github,env-vscode[:mermaid_critical: opt]
ifdef::env-github[:mermaid_br: pass:p[&lt;br&gt;]]
ifndef::env-github[:mermaid_br: pass:p[<br>]]

== Purpose and Scope

This document defines the SystemManager for AITRIOS. +
It applies to version XX of XX.

<<<

== Terminology
None in particular.

<<<

== Component Description
=== Overview of the Component
Provides APIs to access specific data for the App.

<<<

=== Detailed Description of the Component
Receives API calls from the App and performs data retrieval and settings through the ParameterStorageManager.

.Component Diagram
[{mermaid_block}]
....
graph TB;
direction LR

App --> |Get/Set API| SystemManager
SystemManager --> |Data Retrieval/Storage| ParameterStorageManager
....

For the device startup reason notification function and the exception information upload function, the configuration is as shown in the diagram below.

.Component Diagram
[{mermaid_block}]
....
graph TB;
direction LR

EsfMain --> |Device Startup Reason Notification / Exception Information Upload / Determination of Need for System Restart| SystemManager
SystemManager --> |Determination of Need for Restart| PLSystemManager
SystemManager --> |Acquisition of Startup Reasons / Exception Information| PowerManager
SystemManager --> |Elog Output of Startup Reasons| UtilityLog
SystemManager --> |BulkDlog Output of Exception Information| LogManager
....

<<<

=== State Transition
The System Manager does not maintain any state.

<<<

=== List of Component Functions
A list of functions is shown in <<#_TableFunction>>.

[#_TableFunction]
.Function List
[width="100%", cols="30%,55%,15%",options="header"]
|===
|Function Name |Description |Section Number
|Data Retrieval Function
|Retrieves the specified data from the ParameterStorageManager.
|<<#_DataRetrievalFunction>>

|Data Setting Function
|Sets the specified data in the Parameter Storage Manager.
|<<#_DataSettingFunction>>
|Device Startup Reason Notification Function
|Notifies the device startup reason through Elog.
|<<#_ResetCauseNortifyFunction>>
|Exception Information Upload Function
|Uploads exception information to the cloud via BulkDlog.
|<<#_ExceptionInfoUploadFunction>>
|Data Migration Function
|Migrates configuration data from the old format to the new format to maintain compatibility with previous versions.
|<<#_DataMigrationFunction>>
|===

<<<

=== Description of Component Functions
[#_DataRetrievalFunction]
==== Data Retrieval Function
* Function Overview
    ** Retrieves the specified data from the ParameterStorageManager.
* Preconditions
    ** The ParameterStorageManager must be initialized.
* Function Details
    ** Detailed Behavior
        *** Opens the ParameterStorageManager, retrieves the data, closes the ParameterStorageManager, and returns the data.
    ** Behavior in Case of Error and Recovery Method
        *** Returns an error if the API call to the ParameterStorageManager fails.
        *** If the data retrieved from the ParameterStorageManager is empty, a default value defined by the configuration (<<#_ConfigList>>) is returned. +
        If the data must not be empty, no default value configuration is provided, and an error is returned.

[#_DataSettingFunction]
==== Data Setting Function
* Function Overview
    ** Sets the specified data in the ParameterStorageManager.
* Preconditions
    ** The ParameterStorageManager must be initialized.
* Function Details
    ** Detailed Behavior
        *** Opens the ParameterStorageManager, sets the data, and closes the ParameterStorageManager.
    ** Behavior in Case of Error and Recovery Method
        *** Returns an error if the API call to the ParameterStorageManager fails.

[#_ResetCauseNortifyFunction]
==== Device Startup Reason Notification Function
* Function Overview
    ** Provides a function to notify the device startup reason through Elog.
* Prerequisites
    ** The Parameter Storage Manager / Power Manager must be initialized.
* Function Details
    ** Detailed Behavior
        *** Notifies the device startup reason through Elog.
    ** Behavior in Case of Error and Recovery Method
        *** Returns an error if an API call to the Parameter Storage Manager or Power Manager fails.

[#_DeviceResetCauseElogList]
.List of Device Startup Reason Elog Entries
[width="100%",options="header"]
|===
|ID |Description
|0x6001
|System restart due to power supply

|0x6002
|System restart due to voltage drop

|0x6003
|System restart due to normal software reset

|0x6004
|System restart due to abnormal software reset

|0x6005
|System restart due to deep sleep

|0x6006
|System restart due to WDT

|0x6040
|System restart due to EVP memory allocation failure

|0x6041
|System restart due to EVP freeze detection

|===


[#_ExceptionInfoUploadFunction]
==== Exception Information Upload Function
* Function Overview
    ** Provides a function to upload exception information to the cloud via BulkDlog.
* Prerequisites
    ** The Parameter Storage Manager / Power Manager / Log Manager must be initialized.
* Function Details
    ** Detailed Behavior
        *** Consists of two stages: exception information retrieval and upload.
        *** Exception Information Retrieval
        **** By calling ``EsfSystemManagerSetExceptionInfo()``, the startup reason is obtained. +
             There are startup reasons obtained from EVP and those obtained from the Power Manager, with the EVP startup reason taking priority. +
             If the startup reason is “System restart due to WDT,” the Power Manager retrieves the exception information, which is then stored in the Parameter Storage Manager. +
        *** Exception Information Upload
        **** By calling ``EsfSystemManagerUploadExceptionInfo()``, the exception information stored in the Parameter Storage Manager is retrieved and uploaded to the cloud via BulkDlog. +
             After upload completion, the exception information stored in the Parameter Storage Manager is deleted. +
             If no exception information exists, no action is taken.
    ** Behavior in Case of Error and Recovery Method
        *** Returns an error if an API call to the Parameter Storage Manager / Power Manager / Log Manager fails.

[#_DataMigrationFunction]
==== Data Migration Function
* Function Overview
    ** Provides a function to migrate configuration data from the old format to the new format to maintain compatibility with previous versions.
* Prerequisites
    ** The Parameter Storage Manager must be initialized.
* Function Details
    ** Sequentially executes migration for the following data types:
        *** RootAuth: Migration of root certificate data and its SHA-256 hash value
        *** DeviceManifest: Migration of device manifest data
        *** HwInfo: Migration of hardware information data
        *** EVP Setup Info: Migration of EVP setup information (Address/Port)
    ** Deletes old-format data files after the migration is completed.
    ** If the target data is empty, it is treated as a normal completion.

<<<

=== List of Non-Functional Requirements of the Component

A list of non-functional requirements is shown in <<#_TableNonFunction>>.

[#_TableNonFunction]
.List of Non-Functional Requirements
[width="100%", cols="30%,55%,15%",options="header"]
|===
|Requirement Name |Description |Section Number

|Continuous Processing Time
|Maximum processing time required.
|<<#_ContinuousProcessingTime>>

|Stack Memory Usage
|Maximum amount of stack memory used.
|<<#_StackMemoryUsage>>

|Heap Memory Usage
|Maximum amount of heap memory used.
|<<#_HeapMemoryUsage>>

|Static Memory Usage
|Amount of static memory used.
|<<#_StaticMemoryUsage>>

|Number of Threads Used
|Number of threads used.
|<<#_NumberofThreadsUsed>>
|===

<<<

[#_DescriptionofNonFunctionalRequirementsoftheComponent]
=== Description of Non-Functional Requirements of the Component
[#_ContinuousProcessingTime]
==== Continuous Processing Time
The maximum processing time for this component is 10 ms. +
The time required for data access and service configuration that depends on other modules is excluded from this processing time.

[#_StackMemoryUsage]
==== Stack Memory Usage
Uses up to 1024 bytes.

[#_HeapMemoryUsage]
==== Heap Memory Usage
Does not use heap memory.

[#_StaticMemoryUsage]
==== Static Memory Usage
Does not use static memory.

[#_NumberofThreadsUsed]
==== Number of Threads Used
Does not use threads.

<<<

== API Specification
=== Definition List

==== Config List
[#_ConfigList]
.Config List
[width="100%", options="header"]
|===
|Config Name |Description |Default Value
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_DPS_URL
|The default value returned when the DPS URL cannot be read from the Parameter Storage Manager.
|``""``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_COMMON_NAME
|The default value returned when the Common Name cannot be read from the Parameter Storage Manager.
|``""``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_DPS_SCOPE_ID
|The default value returned when the DPS Scope ID cannot be read from the Parameter Storage Manager.
|``""``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_PROJECT_ID
|The default value returned when the Project ID cannot be read from the Parameter Storage Manager.
|``""``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_REGISTER_TOKEN
|The default value returned when the Register Token cannot be read from the Parameter Storage Manager.
|``""``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_EVP_HUB_URL
|The default value returned when the EVP Hub URL cannot be read from the Parameter Storage Manager.
|``""``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_EVP_HUB_PORT
|The default value returned when the EVP Hub Port cannot be read from the Parameter Storage Manager.
|``""``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_IOT_PLATFORM
|The default value returned when the IoT Platform cannot be read from the Parameter Storage Manager.
|``""``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_EVP_TLS
a|
The default value returned when the EVP TLS cannot be read from the Parameter Storage Manager.

* ``"0"``: TLS enabled  
* ``"1"``: TLS disabled  

|``"0"``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_QR_MODE_TIMEOUT_VALUE
|The default value returned when the QR mode timeout value cannot be read from the Parameter Storage Manager.

|``0``

|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_INITIAL_SETTING_FLAG
a|
The default value returned when the InitialSettingFlag cannot be read from the Parameter Storage Manager.

* ``0``: Initial setting not performed  
* ``1``: Initial setting completed  

|``0``

|===

==== Data Type List
<<#_TableDataType>> shows the list of data types.

[#_TableDataType]
.Data Type List
[width="100%", cols="30%,55%,15%",options="header"]
|===
|Data Type Name |Description |Section Number
|EsfSystemManagerResult
|An enumeration type that defines the execution result of the API.
|<<#_EsfSystemManagerResult>>

|ESF_SYSTEM_MANAGER_DEVICE_MANIFEST_MAX_SIZE
|A macro that defines the data size of the Device Manifest.
|<<#_ESF_SYSTEM_MANAGER_DEVICE_MANIFEST_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE
|A macro that defines the data size of the DPS URL.
|<<#_ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE
|A macro that defines the data size of the Common Name.
|<<#_ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE
|A macro that defines the data size of the DPS Scope ID.
|<<#_ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE
|A macro that defines the data size of the Project ID.
|<<#_ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE
|A macro that defines the data size of the Register Token.
|<<#_ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE
|A macro that defines the data size of the EVP Hub URL.
|<<#_ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE
|A macro that defines the data size of the EVP Hub Port.
|<<#_ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE
|A macro that defines the data size of the EVP IoT Platform.
|<<#_ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE>>

|EsfSystemManagerEvpTlsValue
|An enumeration type that defines the configuration values of EVP TLS.
|<<#_EsfSystemManagerEvpTlsValue>>

|ESF_SYSTEM_MANAGER_ROOT_CA_MAX_SIZE
|A macro that defines the data size of the root certificate.
|<<#_ESF_SYSTEM_MANAGER_ROOT_CA_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_ROOT_CA_HASH_MAX_SIZE
|A macro that defines the data size of the root certificate hash value.
|<<#_ESF_SYSTEM_MANAGER_ROOT_CA_HASH_MAX_SIZE>>

|EsfSystemManagerHwInfo
|A structure that contains hardware information data configured on the device.
|<<#_EsfSystemManagerHwInfo>>

|ESF_SYSTEM_MANAGER_HWINFO_MODEL_NAME_MAX_SIZE
|A macro that defines the data size of the HwInfo Model Name.
|<<#_ESF_SYSTEM_MANAGER_HWINFO_MODEL_NAME_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_HWINFO_MANUFACTURER_NAME_MAX_SIZE
|A macro that defines the data size of the HwInfo Manufacturer Name.
|<<#_ESF_SYSTEM_MANAGER_HWINFO_MANUFACTURER_NAME_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_HWINFO_PRODUCT_SERIAL_NUMBER_MAX_SIZE
|A macro that defines the data size of the HwInfo Product Serial Number.
|<<#_ESF_SYSTEM_MANAGER_HWINFO_PRODUCT_SERIAL_NUMBER_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_HWINFO_SERIAL_NUMBER_MAX_SIZE
|A macro that defines the data size of the HwInfo Serial Number.
|<<#_ESF_SYSTEM_MANAGER_HWINFO_SERIAL_NUMBER_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_HWINFO_AIISP_CHIP_ID_MAX_SIZE
|A macro that defines the data size of the HwInfo AIISP Chip ID.
|<<#_ESF_SYSTEM_MANAGER_HWINFO_AIISP_CHIP_ID_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_HWINFO_SENSOR_ID_MAX_SIZE
|A macro that defines the data size of the HwInfo Sensor ID.
|<<#_ESF_SYSTEM_MANAGER_HWINFO_SENSOR_ID_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_HWINFO_APPLICATION_PROCESSOR_TYPE_MAX_SIZE
|A macro that defines the data size of the HwInfo Application Processor Type.
|<<#_ESF_SYSTEM_MANAGER_HWINFO_APPLICATION_PROCESSOR_TYPE_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE
|A macro that defines the data size of the HwInfo Sensor Model Name.
|<<#_ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE>>

|ESF_SYSTEM_MANAGER_HWINFO_DEVICE_NAME_MAX_SIZE
|A macro that defines the data size of the HwInfo Device Name.
|<<#_ESF_SYSTEM_MANAGER_HWINFO_DEVICE_NAME_MAX_SIZE>>

|EsfSystemManagerInitialSettingFlag
|An enumeration type that defines the configuration values of the InitialSettingFlag.
|<<#_EsfSystemManagerInitialSettingFlag>>

|EsfSystemManagerResetCause
|An enumeration type that defines the startup reason values provided by the Power Manager.
|<<#_EsfSystemManagerResetCause>>

|EsfSystemManagerEvpResetCause
|An enumeration type that defines the startup reason values provided by EVP.
|<<#_EsfSystemManagerEvpResetCause>>

|EsfSystemManagerRebootType
|An enumeration type that defines the reboot type values.
|<<#_EsfSystemManagerRebootType>>

|===

[#_APIList]
==== API List
This section shows the list of APIs.

[#_GetAPI]
.List of Retrieval APIs
[width="100%",options="header"]
|===
|API Name |Description |Return Value When Data Is Empty |Section Number
|EsfSystemManagerGetDeviceManifest
|Retrieves the Device Manifest.
|Error
|<<#_EsfSystemManagerGetDeviceManifest>>

|EsfSystemManagerGetProjectId
|Retrieves the Project ID.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_PROJECT_ID
|<<#_EsfSystemManagerGetProjectId>>

|EsfSystemManagerGetDpsUrl
|Retrieves the DPS URL.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_DPS_URL
|<<#_EsfSystemManagerGetDpsUrl>>

|EsfSystemManagerGetCommonName
|Retrieves the Common Name.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_COMMON_NAME
|<<#_EsfSystemManagerGetCommonName>>

|EsfSystemManagerGetDpsScopeId
|Retrieves the DPS Scope ID.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_DPS_SCOPE_ID
|<<#_EsfSystemManagerGetDpsScopeId>>

|EsfSystemManagerGetRegisterToken
|Retrieves the Register Token.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_REGISTER_TOKEN
|<<#_EsfSystemManagerGetRegisterToken>>


|EsfSystemManagerGetEvpHubUrl
|Retrieves the EVP Hub URL.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_EVP_HUB_URL
|<<#_EsfSystemManagerGetEvpHubUrl>>


|EsfSystemManagerGetEvpHubPort
|Retrieves the EVP Hub Port.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_EVP_HUB_PORT
|<<#_EsfSystemManagerGetEvpHubPort>>

|EsfSystemManagerGetEvpIotPlatform
|Retrieves the EVP IoT Platform.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_IOT_PLATFORM
|<<#_EsfSystemManagerGetEvpIotPlatform>>

|EsfSystemManagerGetEvpTls
|Retrieves the EVP TLS setting.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_EVP_TLS
|<<#_EsfSystemManagerGetEvpTls>>


|EsfSystemManagerGetRootCa
|Retrieves the root certificate.
|Error
|<<#_EsfSystemManagerGetRootCa>>

|EsfSystemManagerGetRootCaHash
|Retrieves the root certificate hash value.
|Error
|<<#_EsfSystemManagerGetRootCaHash>>

|EsfSystemManagerGetQrModeTimeoutValue
|Retrieves the QR mode timeout value.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_QR_MODE_TIMEOUT_VALUE
|<<#_EsfSystemManagerGetQrModeTimeoutValue>>

|EsfSystemManagerGetInitialSettingFlag
|Retrieves the InitialSettingFlag.
|CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_INITIAL_SETTING_FLAG
|<<#_EsfSystemManagerGetInitialSettingFlag>>

|EsfSystemManagerGetHwInfo
|Retrieves the hardware information configured on the device.
|Returns empty data
|<<#_EsfSystemManagerGetHwInfo>>

|EsfSystemManagerGetEvpResetCause
|Retrieves the startup reason provided by EVP.
|``kEsfSystemManagerEvpResetCauseClear``
|<<#_EsfSystemManagerGetEvpResetCause>>

|EsfSystemManagerGetResetCause
|Retrieves the startup reason provided by the Power Manager.
|``kEsfSystemManagerResetCauseClear``
|<<#_EsfSystemManagerGetResetCause>>

|===



[#_SetAPI]
.List of Setting APIs
[width="100%",options="header"]
|===
|API Name |Description |Section Number

|EsfSystemManagerSetDpsUrl
|Sets the DPS URL.
|<<#_EsfSystemManagerSetDpsUrl>>

|EsfSystemManagerSetCommonName
|Sets the Common Name.
|<<#_EsfSystemManagerSetCommonName>>

|EsfSystemManagerSetDpsScopeId
|Sets the DPS Scope ID.
|<<#_EsfSystemManagerSetDpsScopeId>>

|EsfSystemManagerSetProjectId
|Sets the Project ID.
|<<#_EsfSystemManagerSetProjectId>>

|EsfSystemManagerSetRegisterToken
|Sets the Register Token.
|<<#_EsfSystemManagerSetRegisterToken>>

|EsfSystemManagerSetEvpHubUrl
|Sets the EVP Hub URL.
|<<#_EsfSystemManagerSetEvpHubUrl>>

|EsfSystemManagerSetEvpHubPort
|Sets the EVP Hub Port.
|<<#_EsfSystemManagerSetEvpHubPort>>

|EsfSystemManagerSetEvpTls
|Sets the EVP TLS value.
|<<#_EsfSystemManagerSetEvpTls>>

|EsfSystemManagerSetEvpIotPlatform
|Sets the EVP IoT Platform.
|<<#_EsfSystemManagerSetEvpIotPlatform>>

|EsfSystemManagerSetQrModeTimeoutValue
|Saves the QR mode timeout value.
|<<#_EsfSystemManagerSetQrModeTimeoutValue>>

|EsfSystemManagerSetInitialSettingFlag
|Sets the InitialSettingFlag.
|<<#_EsfSystemManagerSetInitialSettingFlag>>

|EsfSystemManagerSetEvpResetCause
|Sets the startup reason provided by EVP.
|<<#_EsfSystemManagerSetEvpResetCause>>

|EsfSystemManagerSetResetCause
|Sets the startup reason provided by the Power Manager.
|<<#_EsfSystemManagerSetResetCause>>
|===

[#_OtherAPI]
.List of Other APIs
[width="100%",options="header"]
|===
|API Name |Description |Section Number

|EsfSystemManagerSetExceptionInfo
|Saves the startup reason and exception information.
|<<#_EsfSystemManagerSetExceptionInfo>>

|EsfSystemManagerSendResetCause
|Notifies the startup reason through Elog.
|<<#_EsfSystemManagerSendResetCause>>

|EsfSystemManagerUploadExceptionInfo
|Uploads exception information to the cloud via BulkDlog.
|<<#_EsfSystemManagerUploadExceptionInfo>>

|EsfSystemManagerIsNeedReboot
|Determines whether a system reboot is required based on the startup reason.
|<<#_EsfSystemManagerIsNeedReboot>>

|EsfSystemManagerExecReboot
|Executes a system reboot with the specified reboot type.
|<<#_EsfSystemManagerExecReboot>>

|EsfSystemManagerMigration
|Executes the migration process for System Manager configuration data.
|<<#_EsfSystemManagerMigration>>

|===


<<<

=== Data Type Definitions
[#_EsfSystemManagerResult]
==== EsfSystemManagerResult
Enumeration defining the result of API execution.

* *Format*

[source, C]
....
typedef enum {
  kEsfSystemManagerResultOk,
  kEsfSystemManagerResultParamError,
  kEsfSystemManagerResultInternalError,
  kEsfSystemManagerResultOutOfRange,
  kEsfSystemManagerResultEmptyData,
} EsfSystemManagerResult;
....


* *Values*

[#_TableReturnValue]
.Description of EsfSystemManagerResult Values
[width="100%", cols="30%,70%",options="header"]
|===
|Member Name |Description
|kEsfSystemManagerResultOk
|Processing succeeded.

|kEsfSystemManagerResultParamError
|An invalid argument was passed.

|kEsfSystemManagerResultInternalError
|An internal error occurred.

|kEsfSystemManagerResultOutOfRange
|The data size is out of the allowable range.

|kEsfSystemManagerResultEmptyData
|No data is stored for the requested item.

|===

[#_ESF_SYSTEM_MANAGER_DEVICE_MANIFEST_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_DEVICE_MANIFEST_MAX_SIZE
Macro defining the maximum size of the Device Manifest.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_DEVICE_MANIFEST_MAX_SIZE (32768)
....

[#_ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE
Macro defining the maximum size of the DPS URL.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE (256)
....

[#_ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE
Macro defining the maximum size of the Common Name.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE (256)
....

[#_ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE
Macro defining the maximum size of the DPS Scope ID.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE (17)
....

[#_ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE
Macro defining the maximum size of the Project ID.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE (33)
....

[#_ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE
Macro defining the maximum size of the Register Token.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE (45)
....

[#_ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE
Macro defining the maximum size of the EVP Hub URL.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE (65)
....

[#_ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE
Macro defining the maximum size of the EVP Hub Port.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE (6)
....

[#_ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE
Macro defining the maximum size of the EVP IoT Platform.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE (33)
....

[#_EsfSystemManagerEvpTlsValue]
==== EsfSystemManagerEvpTlsValue
Enumeration defining the configuration values for EVP TLS.

* *Format*

[source, C]
....
typedef enum {
    kEsfSystemManagerEvpTlsDisable,
    kEsfSystemManagerEvpTlsEnable
} EsfSystemManagerEvpTlsValue;
....

* *Values*

.Description of EsfSystemManagerEvpTlsValue Values
[width="100%", cols="30%,70%",options="header"]
|===
|Member Name |Description
|kEsfSystemManagerEvpTlsDisable
|EVP TLS disabled

|kEsfSystemManagerEvpTlsEnable
|EVP TLS enabled
|===


[#_ESF_SYSTEM_MANAGER_ROOT_CA_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_ROOT_CA_MAX_SIZE
Macro defining the maximum size of the Root Certificate.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_ROOT_CA_MAX_SIZE (393216)
....

[#_ESF_SYSTEM_MANAGER_ROOT_CA_HASH_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_ROOT_CA_HASH_MAX_SIZE
Macro defining the maximum size of the Root Certificate hash value.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_ROOT_CA_HASH_MAX_SIZE (512)
....

[#_EsfSystemManagerHwInfo]
==== EsfSystemManagerHwInfo
Structure that holds data related to HW information set on the device.

* *Format*

[source, C]
....
typedef struct EsfSystemManagerHwInfo{
  char model_name[ESF_SYSTEM_MANAGER_HWINFO_MODEL_NAME_MAX_SIZE];
  char manufacturer_name[ESF_SYSTEM_MANAGER_HWINFO_MANUFACTURER_NAME_MAX_SIZE];
  char product_serial_number[ESF_SYSTEM_MANAGER_HWINFO_PRODUCT_SERIAL_NUMBER_MAX_SIZE];
  char serial_number[ESF_SYSTEM_MANAGER_HWINFO_SERIAL_NUMBER_MAX_SIZE];
  char aiisp_chip_id[ESF_SYSTEM_MANAGER_HWINFO_AIISP_CHIP_ID_MAX_SIZE];
  char sensor_id[ESF_SYSTEM_MANAGER_HWINFO_SENSOR_ID_MAX_SIZE];
  char application_processor_type[ESF_SYSTEM_MANAGER_HWINFO_APPLICATION_PROCESSOR_TYPE_MAX_SIZE];
  char sensor_model_name[ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE];
  char device_name[ESF_SYSTEM_MANAGER_HWINFO_DEVICE_NAME_MAX_SIZE];
} EsfSystemManagerHwInfo;
....

* *Values*

.Description of EsfSystemManagerHwInfo Members
[width="100%", cols="30%,70%",options="header"]
|===
|Member Name |Description
|model_name
|Model Name

|manufacturer_name
|Manufacturer Name

|product_serial_number
|Product Serial Number

|serial_number
|Serial Number

|aiisp_chip_id
|AIISP Chip ID

|sensor_id
|Sensor ID

|application_processor_type
|Application Processor Type

|sensor_model_name
|Sensor Model Name

|device_name
|Device Name
|===


[#_ESF_SYSTEM_MANAGER_HWINFO_MODEL_NAME_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_MODEL_NAME_MAX_SIZE
Macro defining the data size of the HW Info Model Name.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_MODEL_NAME_MAX_SIZE (33)
....


[#_ESF_SYSTEM_MANAGER_HWINFO_MANUFACTURER_NAME_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_MANUFACTURER_NAME_MAX_SIZE
Macro defining the data size of the HW Info Manufacturer Name.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_MANUFACTURER_NAME_MAX_SIZE (33)
....


[#_ESF_SYSTEM_MANAGER_HWINFO_PRODUCT_SERIAL_NUMBER_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_PRODUCT_SERIAL_NUMBER_MAX_SIZE
Macro defining the data size of the HW Info Product Serial Number.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_PRODUCT_SERIAL_NUMBER_MAX_SIZE (33)
....

[#_ESF_SYSTEM_MANAGER_HWINFO_SERIAL_NUMBER_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_SERIAL_NUMBER_MAX_SIZE
Macro defining the data size of the HW Info Serial Number.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_SERIAL_NUMBER_MAX_SIZE (64)
....

[#_ESF_SYSTEM_MANAGER_HWINFO_AIISP_CHIP_ID_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_AIISP_CHIP_ID_MAX_SIZE
Macro defining the data size of the HW Info AIISP Chip ID.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_AIISP_CHIP_ID_MAX_SIZE (37)
....

[#_ESF_SYSTEM_MANAGER_HWINFO_SENSOR_ID_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_SENSOR_ID_MAX_SIZE
Macro defining the data size of the HW Info Sensor ID.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_SENSOR_ID_MAX_SIZE (37)
....

[#_ESF_SYSTEM_MANAGER_HWINFO_APPLICATION_PROCESSOR_TYPE_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_APPLICATION_PROCESSOR_TYPE_MAX_SIZE
Macro defining the data size of the HW Info Application Processor Type.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_APPLICATION_PROCESSOR_TYPE_MAX_SIZE (64)
....

[#_ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE
Macro defining the data size of the HW Info Sensor Model Name.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE (64)
....

[#_ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE
A macro that defines the data size of the HwInfo Sensor Model Name.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE (64)
....

[#_ESF_SYSTEM_MANAGER_HWINFO_DEVICE_NAME_MAX_SIZE]
==== ESF_SYSTEM_MANAGER_HWINFO_DEVICE_NAME_MAX_SIZE
A macro that defines the data size of the HwInfo Device Name.

* *Format*

[source, C]
....
#define ESF_SYSTEM_MANAGER_HWINFO_DEVICE_NAME_MAX_SIZE (33)
....


[#_EsfSystemManagerInitialSettingFlag]
==== EsfSystemManagerInitialSettingFlag
Enumeration defining the configuration values for InitialSettingFlag.

* *Format*

[source, C]
....
typedef enum {
  kEsfSystemManagerInitialSettingNotCompleted,
  kEsfSystemManagerInitialSettingCompleted
} EsfSystemManagerInitialSettingFlag;
....

* *Values*

.Description of EsfSystemManagerInitialSettingFlag Values
[width="100%", cols="30%,70%",options="header"]
|===
|Member Name |Description
|kEsfSystemManagerInitialSettingNotCompleted
|Initial setting not completed

|kEsfSystemManagerInitialSettingCompleted
|Initial setting completed
|===

[#_EsfSystemManagerResetCause]
==== EsfSystemManagerResetCause
An enumeration type that defines the startup reasons provided by the Power Manager.

* *Format*

[source, C]
....
typedef enum {
  kEsfSystemManagerResetCauseUnknown = -1,
  kEsfSystemManagerResetCauseSysChipPowerOnReset = 0,
  kEsfSystemManagerResetCauseSysBrownOut,
  kEsfSystemManagerResetCauseCoreSoft,
  kEsfSystemManagerResetCauseCoreDeepSleep,
  kEsfSystemManagerResetCauseWDT,
  kEsfSystemManagerResetCauseSoftResetNormal,
  kEsfSystemManagerResetCauseSoftResetError,
  kEsfSystemManagerResetCauseDefault,
  kEsfSystemManagerResetCauseClear,
  kEsfSystemManagerResetCauseMax
} EsfSystemManagerResetCause;
....

* *Values* 

.Description of EsfSystemManagerResetCause Values
[width="100%", cols="30%,70%",options="header"]
|===
|Member Name |Description
|kEsfSystemManagerResetCauseUnknown
|Unsupported reset cause.

|kEsfSystemManagerResetCauseSysChipPowerOnReset
|System restart due to power supply.

|kEsfSystemManagerResetCauseSysBrownOut
|System restart due to voltage drop.

|kEsfSystemManagerResetCauseCoreSoft
|software core reset

|kEsfSystemManagerResetCauseCoreDeepSleep
|System restart due to deep sleep.

|kEsfSystemManagerResetCauseWDT
|System restart due to WDT.

|kEsfSystemManagerResetCauseSoftResetNormal
|System restart due to normal software reset.

|kEsfSystemManagerResetCauseSoftResetError
|System restart due to abnormal software reset.

|kEsfSystemManagerResetCauseDefault
|Default state where no startup reason is set.

|kEsfSystemManagerResetCauseClear
a|
* When setting: Deletes the startup reason provided by the Power Manager.
* When getting: No startup reason provided by the Power Manager exists.

|kEsfSystemManagerResetCauseMax
|Maximum number of elements.
|===


[#_EsfSystemManagerEvpResetCause]
==== EsfSystemManagerEvpResetCause
An enumeration type that defines the startup reasons provided by EVP.

* *Format*

[source, C]
....
typedef enum {
  kEsfSystemManagerEvpResetCauseClear,
  kEsfSystemManagerEvpResetCauseMemoryAllocFailure,
  kEsfSystemManagerEvpResetCauseFreezeDetection,
  kEsfSystemManagerEvpResetCauseMax,
} EsfSystemManagerEvpResetCause;
....

* *Values* 

.Description of EsfSystemManagerEvpResetCause Values
[width="100%", cols="30%,70%",options="header"]
|===
|Member Name |Description
|kEsfSystemManagerEvpResetCauseClear
a|
* When setting: Disables the startup reason provided by EVP.
* When getting: No startup reason provided by EVP.

|kEsfSystemManagerEvpResetCauseMemoryAllocFailure
|Memory allocation failure.

|kEsfSystemManagerEvpResetCauseFreezeDetection
|Freeze detection.

|kEsfSystemManagerEvpResetCauseMax
|Maximum number of elements.
|===


[#_EsfSystemManagerRebootType]
==== EsfSystemManagerRebootType
An enumeration type that defines the reboot type values.

* *Format*

[source, C]
....
typedef enum {
  kEsfSystemManagerRebootTypeSystemNormal,
  kEsfSystemManagerRebootTypeSystemAbnormal,
  kEsfSystemManagerRebootTypeEvpMemoryAllocFailure,
  kEsfSystemManagerRebootTypeEvpFreezeDetection,
  kEsfSystemManagerRebootTypeMax
} EsfSystemManagerRebootType;
....

* *Values*

.Description of EsfSystemManagerRebootType Values
[width="100%", cols="30%,70%",options="header"]
|===
|Member Name |Description
|kEsfSystemManagerRebootTypeSystemNormal
|Normal system reboot.

|kEsfSystemManagerRebootTypeSystemAbnormal
|Abnormal system reboot.

|kEsfSystemManagerRebootTypeEvpMemoryAllocFailure
|EVP memory allocation failure.

|kEsfSystemManagerRebootTypeEvpFreezeDetection
|EVP freeze detection.

|kEsfSystemManagerRebootTypeMax
|Maximum number of elements.
|===

<<<

=== API Definitions

[#_EsfSystemManagerGetDeviceManifest]
==== EsfSystemManagerGetDeviceManifest
* *Function* 
+
Retrieves the Device Manifest.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetDeviceManifest( char *data, size_t *data_size )**``

* *Parameter Description* +
+
**``[OUT] char *data``**::  
Pass the starting address of the memory area to store the retrieved Device Manifest (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**::  
Specify the size of the `data` buffer. +  
The value must be 1 or more, including the terminating null character (`'\0'`). +  
After the API call, the actual size of the valid data retrieved (including the null terminator) will be stored in `*data_size`. +  
If `*data_size` is smaller than the actual valid data size, the function returns `kEsfSystemManagerResultOutOfRange`. To avoid this, specify a buffer size equal to or greater than `ESF_SYSTEM_MANAGER_DEVICE_MANIFEST_MAX_SIZE`. +  
If `0` or `NULL` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result of the execution.

* *Description* +
** Retrieves the Device Manifest and stores it in `data`.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerGetDeviceManifestReturnValue]
.Description of Return Values for EsfSystemManagerGetDeviceManifest
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data_size == NULL`
* `*data_size == 0`
|Unchanged.
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|May contain undefined values.
|Cannot be recovered.

|kEsfSystemManagerResultOutOfRange
|`*data_size` is smaller than the size of the data retrieved.
|May contain undefined values.
|Specify a sufficient `*data_size` and retry.

|kEsfSystemManagerResultEmptyData
|No Device Manifest is stored in the ParameterStorageManager.
|Unchanged.
|Store a valid Device Manifest before retrying.

|===

[#_EsfSystemManagerGetDpsUrl]
==== EsfSystemManagerGetDpsUrl
* *Function* 
+
Retrieves the DPS URL.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetDpsUrl( char *data, size_t *data_size )**``

* *Parameter Description* +
+
**``[OUT] char *data``**::  
Pass the starting address of the memory area to store the retrieved DPS URL (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**::  
Specify the size of the `data` buffer. +  
The value must be 1 or more, including the null terminator (`'\0'`). +  
After the API call, the actual size of the valid data retrieved (including the null terminator) will be stored in `*data_size`. +  
If `*data_size` is smaller than the size of the retrieved data, the function returns `kEsfSystemManagerResultOutOfRange`. To avoid this, specify a buffer size equal to or greater than `ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE`. +  
If `0` or `NULL` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result of the execution.

* *Description* +
** Retrieves the DPS URL and stores it in `data`.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerGetDpsUrlReturnValue]
.Description of Return Values for EsfSystemManagerGetDpsUrl
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data_size == NULL`
* `*data_size == 0`
|Unchanged.
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|May contain undefined values.
|Cannot be recovered.

|kEsfSystemManagerResultOutOfRange
|`*data_size` is smaller than the size of the retrieved data.
|May contain undefined values.
|Specify a sufficient `*data_size` and retry.

|===


[#_EsfSystemManagerSetDpsUrl]
==== EsfSystemManagerSetDpsUrl
* *Function* 
+
Sets the DPS URL.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetDpsUrl( const char *data, size_t data_size )**``

* *Parameter Description* +
+
**``[IN] const char *data``**::  
The string representing the DPS URL to be set. +  
Specify the starting address of a null-terminated string. +  
A string up to `ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE` in size can be set.  
**``[IN] size_t data_size``**::  
Specify the size of the `data` string, including the null terminator. +  
If `0` or a value larger than `ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result of the execution.

* *Description* +
** Sets the DPS URL string.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerSetDpsUrlReturnValue]
.Description of Return Values for EsfSystemManagerSetDpsUrl
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data` is not null-terminated
* `data_size == 0`
* `data_size > ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE`
|-
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|-
|Cannot be recovered.

|===


[#_EsfSystemManagerGetCommonName]
==== EsfSystemManagerGetCommonName

* *Function* 
+
Retrieves the Common Name.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetCommonName( char *data, size_t *data_size )**``

* *Parameter Description* +
+
**``[OUT] char *data``**::  
Pass the starting address of the memory area to store the retrieved Common Name (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**::  
Specify the size of the `data` buffer. +  
The value must be 1 or more, including the null terminator (`'\0'`). +  
After the API call, the actual size of the valid data retrieved (including the null terminator) will be stored in `*data_size`. +  
If `*data_size` is smaller than the size of the retrieved data, the function returns `kEsfSystemManagerResultOutOfRange`. To avoid this, specify a buffer size equal to or greater than `ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE`. +  
If `0` or `NULL` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result of the execution.

* *Description* +
** Retrieves the Common Name and stores it in `data`.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerGetCommonNameReturnValue]
.Description of Return Values for EsfSystemManagerGetCommonName
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data_size == NULL`
* `*data_size == 0`
|Unchanged.
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|May contain undefined values.
|Cannot be recovered.

|kEsfSystemManagerResultOutOfRange
|`*data_size` is smaller than the size of the retrieved data.
|May contain undefined values.
|Specify a sufficient `*data_size` and retry.

|===


[#_EsfSystemManagerSetCommonName]
==== EsfSystemManagerSetCommonName
* *Function* 
+
Sets the Common Name.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetCommonName( const char *data, size_t data_size )**``

* *Parameter Description* +
+
**``[IN] const char *data``**::  
The string representing the Common Name to be set. +  
Specify the starting address of a null-terminated string. +  
A string up to `ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE` in size can be set.  
**``[IN] size_t data_size``**::  
Specify the size of the `data` string, including the null terminator. +  
If `0` or a value larger than `ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result of the execution.

* *Description* +
** Sets the Common Name string.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerSetCommonNameReturnValue]
.Description of Return Values for EsfSystemManagerSetCommonName
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data` is not null-terminated
* `data_size == 0`
* `data_size > ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE`
|-
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|-
|Cannot be recovered.

|===


[#_EsfSystemManagerGetDpsScopeId]
==== EsfSystemManagerGetDpsScopeId

* *Function* +
Retrieves the DPS Scope ID.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetDpsScopeId( char *data, size_t *data_size )**``

* *Parameter Description* +
+
**``[OUT] char *data``**::  
Pass the starting address of the memory area to store the retrieved DPS Scope ID (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**::  
Specify the size of the `data` buffer. +  
The value must be 1 or more, including the null terminator (`'\0'`). +  
After the API call, the actual size of the valid data retrieved (including the null terminator) will be stored in `*data_size`. +  
If `*data_size` is smaller than the size of the retrieved data, the function returns `kEsfSystemManagerResultOutOfRange`. To avoid this, specify a buffer size equal to or greater than `ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE`. +  
If `0` or `NULL` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Retrieves the DPS Scope ID and stores it in `data`.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerGetDpsScopeIdReturnValue]
.Description of Return Values for EsfSystemManagerGetDpsScopeId
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data_size == NULL`
* `*data_size == 0`
|Unchanged.
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|May contain undefined values.
|Cannot be recovered.

|kEsfSystemManagerResultOutOfRange
|`*data_size` is smaller than the size of the retrieved data.
|May contain undefined values.
|Specify a sufficient `*data_size` and retry.

|===


[#_EsfSystemManagerSetDpsScopeId]
==== EsfSystemManagerSetDpsScopeId

* *Function* +
Sets the DPS Scope ID.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetDpsScopeId( const char *data, size_t data_size )**``

* *Parameter Description* +
+
**``[IN] const char *data``**::  
The string representing the DPS Scope ID to be set. +  
Specify the starting address of a null-terminated string. +  
A string up to `ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE` in size can be set.  
**``[IN] size_t data_size``**::  
Specify the size of the `data` string, including the null terminator. +  
If `0` or a value larger than `ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Sets the DPS Scope ID string.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerSetDpsScopeIdReturnValue]
.Description of Return Values for EsfSystemManagerSetDpsScopeId
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data` is not null-terminated
* `data_size == 0`
* `data_size > ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE`
|-
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|-
|Cannot be recovered.

|===


[#_EsfSystemManagerGetProjectId]
==== EsfSystemManagerGetProjectId
* *Function* 
+
Retrieves the Project ID.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetProjectId( char *data, size_t *data_size )**``

* *Parameter Description* +
+
**``[OUT] char *data``**::  
Pass the starting address of the memory area to store the retrieved Project ID (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**::  
Specify the size of the `data` buffer. +  
The value must be 1 or more, including the null terminator (`'\0'`). +  
After the API call, the actual size of the valid data retrieved (including the null terminator) will be stored in `*data_size`. +  
If `*data_size` is smaller than the size of the retrieved data, the function returns `kEsfSystemManagerResultOutOfRange`. To avoid this, specify a buffer size equal to or greater than `ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE`. +  
If `0` or `NULL` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Retrieves the Project ID and stores it in `data`.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerGetProjectIdReturnValue]
.Description of Return Values for EsfSystemManagerGetProjectId
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data_size == NULL`
* `*data_size == 0`
|Unchanged.
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|May contain undefined values.
|Cannot be recovered.

|kEsfSystemManagerResultOutOfRange
|`*data_size` is smaller than the size of the retrieved data.
|May contain undefined values.
|Specify a sufficient `*data_size` and retry.

|===


[#_EsfSystemManagerSetProjectId]
==== EsfSystemManagerSetProjectId
* *Function* 
+
Sets the Project ID.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetProjectId( const char *data, size_t data_size )**``

* *Parameter Description* +
+
**``[IN] const char *data``**::  
The string representing the Project ID to be set. +  
Specify the starting address of a null-terminated string. +  
A string up to `ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE` in size can be set.  
**``[IN] size_t data_size``**::  
Specify the size of the `data` string, including the null terminator. +  
If `0` or a value larger than `ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Sets the Project ID string.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerSetProjectIdReturnValue]
.Description of Return Values for EsfSystemManagerSetProjectId
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data` is not null-terminated
* `data_size == 0`
* `data_size > ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE`
|-
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|-
|Cannot be recovered.

|===


[#_EsfSystemManagerGetRegisterToken]
==== EsfSystemManagerGetRegisterToken

* *Function* +
Retrieves the Register Token.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetRegisterToken( char *data, size_t *data_size )**``

* *Parameter Description* +
+
**``[OUT] char *data``**::  
Pass the starting address of the memory area to store the retrieved Register Token (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**::  
Specify the size of the `data` buffer. +  
The value must be 1 or more, including the null terminator (`'\0'`). +  
After the API call, the actual size of the valid data retrieved (including the null terminator) will be stored in `*data_size`. +  
If `*data_size` is smaller than the size of the retrieved data, the function returns `kEsfSystemManagerResultOutOfRange`. To avoid this, specify a buffer size equal to or greater than `ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE`. +  
If `0` or `NULL` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Retrieves the Register Token and stores it in `data`.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerGetRegisterTokenReturnValue]
.Description of Return Values for EsfSystemManagerGetRegisterToken
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data_size == NULL`
* `*data_size == 0`
|Unchanged.
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|May contain undefined values.
|Cannot be recovered.

|kEsfSystemManagerResultOutOfRange
|`*data_size` is smaller than the size of the retrieved data.
|May contain undefined values.
|Specify a sufficient `*data_size` and retry.

|===


[#_EsfSystemManagerSetRegisterToken]
==== EsfSystemManagerSetRegisterToken
* *Function* 
+
Sets the Register Token.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetRegisterToken( const char *data, size_t data_size )**``

* *Parameter Description* +
+
**``[IN] const char *data``**::  
The string representing the Register Token to be set. +  
Specify the starting address of a null-terminated string. +  
A string up to `ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE` in size can be set.  
**``[IN] size_t data_size``**::  
Specify the size of the `data` string, including the null terminator. +  
If `0` or a value larger than `ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Sets the Register Token string.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerSetRegisterTokenReturnValue]
.Description of Return Values for EsfSystemManagerSetRegisterToken
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data` is not null-terminated
* `data_size == 0`
* `data_size > ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE`
|-
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|-
|Cannot be recovered.

|===


[#_EsfSystemManagerGetEvpHubUrl]
==== EsfSystemManagerGetEvpHubUrl

* *Function* +
Retrieves the EVP Hub URL.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetEvpHubUrl( char *data, size_t *data_size )**``

* *Parameter Description* +
+
**``[OUT] char *data``**::  
Pass the starting address of the memory area to store the retrieved EVP Hub URL (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**::  
Specify the size of the `data` buffer. +  
The value must be 1 or more, including the null terminator (`'\0'`). +  
After the API call, the actual size of the valid data retrieved (including the null terminator) will be stored in `*data_size`. +  
If `*data_size` is smaller than the size of the retrieved data, the function returns `kEsfSystemManagerResultOutOfRange`. To avoid this, specify a buffer size equal to or greater than `ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE`. +  
If `0` or `NULL` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Retrieves the EVP Hub URL and stores it in `data`.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerGetEvpHubUrlReturnValue]
.Description of Return Values for EsfSystemManagerGetEvpHubUrl
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data_size == NULL`
* `*data_size == 0`
|Unchanged.
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|May contain undefined values.
|Cannot be recovered.

|kEsfSystemManagerResultOutOfRange
|`*data_size` is smaller than the size of the retrieved data.
|May contain undefined values.
|Specify a sufficient `*data_size` and retry.

|===


[#_EsfSystemManagerSetEvpHubUrl]
==== EsfSystemManagerSetEvpHubUrl

* *Function* +
Sets the EVP Hub URL.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetEvpHubUrl( const char *data, size_t data_size )**``

* *Parameter Description* +
+
**``[IN] const char *data``**::  
The string representing the EVP Hub URL to be set. +  
Specify the starting address of a null-terminated string. +  
A string up to `ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE` in size can be set.  
**``[IN] size_t data_size``**::  
Specify the size of the `data` string, including the null terminator. +  
If `0` or a value larger than `ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Sets the EVP Hub URL string.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerSetEvpHubUrlReturnValue]
.Description of Return Values for EsfSystemManagerSetEvpHubUrl
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data` is not null-terminated
* `data_size == 0`
* `data_size > ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE`
|-
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|-
|Cannot be recovered.

|===


[#_EsfSystemManagerGetEvpHubPort]
==== EsfSystemManagerGetEvpHubPort

* *Function* +
Retrieves the EVP Hub Port.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetEvpHubPort( char *data, size_t *data_size )**``

* *Parameter Description* +
+
**``[OUT] char *data``**::  
Pass the starting address of the memory area to store the retrieved EVP Hub Port (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**::  
Specify the size of the `data` buffer. +  
The value must be 1 or more, including the null terminator (`'\0'`). +  
After the API call, the actual size of the valid data retrieved (including the null terminator) will be stored in `*data_size`. +  
If `*data_size` is smaller than the size of the retrieved data, the function returns `kEsfSystemManagerResultOutOfRange`. To avoid this, specify a buffer size equal to or greater than `ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE`. +  
If `0` or `NULL` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Retrieves the EVP Hub Port and stores it in `data`.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerGetEvpHubPortReturnValue]
.Description of Return Values for EsfSystemManagerGetEvpHubPort
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data_size == NULL`
* `*data_size == 0`
|Unchanged.
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|May contain undefined values.
|Cannot be recovered.

|kEsfSystemManagerResultOutOfRange
|`*data_size` is smaller than the size of the retrieved data.
|May contain undefined values.
|Specify a sufficient `*data_size` and retry.

|===


[#_EsfSystemManagerSetEvpHubPort]
==== EsfSystemManagerSetEvpHubPort

* *Function* +
Sets the EVP Hub Port.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetEvpHubPort( const char *data, size_t data_size )**``

* *Parameter Description* +
+
**``[IN] const char *data``**::  
The string representing the EVP Hub Port to be set. +  
Specify the starting address of a null-terminated string. +  
A string up to `ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE` in size can be set.  
**``[IN] size_t data_size``**::  
Specify the size of the `data` string, including the null terminator. +  
If `0` or a value larger than `ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE` is specified, the function returns `kEsfSystemManagerResultParamError`.

* *Return Value* +
+
One of the values listed in <<#_TableReturnValue>> will be returned depending on the result.

* *Description* +
** Sets the EVP Hub Port string.  
** Execution Notes  
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Internally performs blocking.  
** Error Information 
+
[#_EsfSystemManagerSetEvpHubPortReturnValue]
.Description of Return Values for EsfSystemManagerSetEvpHubPort
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* `data == NULL`
* `data` is not null-terminated
* `data_size == 0`
* `data_size > ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE`
|-
|Set valid parameters and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.
|-
|Cannot be recovered.

|===


[#_EsfSystemManagerGetEvpIotPlatform]
==== EsfSystemManagerGetEvpIotPlatform
* *Function* 
+
Retrieves the EVP IoT Platform.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetEvpIotPlatform( char *data, size_t *data_size )**``  

* *Arguments* +
+
**``[OUT] char *data``**:: 
Specify the starting address of the area to store the retrieved EVP IoT Platform (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**:: 
Specify the size of the ``data`` buffer. +
The value must be at least ``1``, including the null-terminator. +
After the API call, the actual size of the valid data retrieved (including the null-terminator) will be stored. +
If ``*data_size`` is insufficient for the valid data, the function returns ``kEsfSystemManagerResultOutOfRange``. +
If you specify a buffer size equal to or greater than ``ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE``, the size will be sufficient. +
If ``0`` or ``NULL`` is specified, the function returns ``kEsfSystemManagerResultParamError``.

* *Return Value* +
+
One of the values in <<#_TableReturnValue>> is returned depending on the execution result.

* *Description* +
** Retrieves the EVP IoT Platform and stores it in ``data``.  
** Execution details  
*** Can be called concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerGetEvpIotPlatformReturnValue]
.Description of return values for EsfSystemManagerGetEvpIotPlatform
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
a|
* ``data == NULL``  
* ``data_size == NULL``  
* ``*data_size == 0``  
|Unchanged  
|Set the correct argument values and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|The output may contain undefined values.  
|Not recoverable.

|kEsfSystemManagerResultOutOfRange
|``*data_size`` is smaller than the size of the actual retrieved data.  
|The output may contain undefined values.  
|Specify a sufficiently large ``*data_size`` and retry.  
|===


[#_EsfSystemManagerSetEvpIotPlatform]
==== EsfSystemManagerSetEvpIotPlatform
* *Function* 
+
Sets the EVP IoT Platform.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetEvpIotPlatform( const char *data, size_t data_size )**``  

* *Arguments* +
+
**``[IN] const char *data``**:: 
The string representing the EVP IoT Platform to set. +
Specify the starting address of a null-terminated string. +
The maximum allowable size is ``ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE``.
**``[IN] size_t data_size``**:: 
Specify the size of the ``data`` string including the null-terminator. +
If ``0`` or a value greater than ``ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE`` is specified, the function returns ``kEsfSystemManagerResultParamError``.

* *Return Value* +
+
One of the values in <<#_TableReturnValue>> is returned depending on the execution result.

* *Description* +
** Sets the EVP IoT Platform string.  
** Execution details  
*** Can be called concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerSetEvpIotPlatformReturnValue]
.Description of return values for EsfSystemManagerSetEvpIotPlatform
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
a|
* ``data == NULL``  
* ``data`` is not null-terminated  
* ``data_size == 0``  
* ``data_size > ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE``  
|-  
|Set the correct argument values and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|-  
|Not recoverable.  
|===


[#_EsfSystemManagerGetEvpTls]
==== EsfSystemManagerGetEvpTls
* *Function* 
+
Retrieves the EVP TLS setting.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetEvpTls( EsfSystemManagerEvpTlsValue *data )**``  

* *Arguments* +
+
**``[OUT] EsfSystemManagerEvpTlsValue *data``**:: 
The retrieved EVP TLS setting will be stored in this variable.

* *Return Value* +
+
One of the values in <<#_TableReturnValue>> is returned depending on the execution result.

* *Description* +
** Retrieves the EVP TLS setting and stores it in ``data``.  
** Execution details  
*** Can be called concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerGetEvpTlsReturnValue]
.Description of return values for EsfSystemManagerGetEvpTls
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
|``data == NULL``  
|Unchanged  
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|The output may contain undefined values.  
|Not recoverable.

|kEsfSystemManagerResultOutOfRange
|An invalid value was retrieved from the ParameterStorageManager.  
|Unchanged  
|Write the correct value beforehand.  
|===


[#_EsfSystemManagerSetEvpTls]
==== EsfSystemManagerSetEvpTls
* *Function* 
+
Sets the EVP TLS.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetEvpTls( EsfSystemManagerEvpTlsValue data )**``  

* *Arguments* +
+
**``[IN] EsfSystemManagerEvpTlsValue data``**:: 
The value to set for the EVP TLS setting.

* *Return Value* +
+
One of the values in <<#_TableReturnValue>> is returned depending on the execution result.

* *Description* +
** Sets the EVP TLS as enabled or disabled.  
** Execution details  
*** Can be called concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerSetEvpTlsReturnValue]
.Description of return values for EsfSystemManagerSetEvpTls
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
|The ``data`` value contains an invalid enum value.  
|-  
|Set the correct value and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|-  
|Not recoverable.  
|===


[#_EsfSystemManagerGetRootCa]
==== EsfSystemManagerGetRootCa
* *Function* 
+
Retrieves the Root Certificate.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetRootCa( char *data, size_t *data_size )**``  

* *Arguments* +
+
**``[OUT] char *data``**:: 
Specify the starting address of the area to store the retrieved Root Certificate (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**:: 
Specify the size of ``data``. +
The value must be ``1`` or greater, including the null-terminator. +
After this API is executed, the actual size of the retrieved valid data (including the null-terminator) is stored. +
If ``*data_size`` is smaller than the size of the valid data, ``kEsfSystemManagerResultOutOfRange`` is returned. +
If a size equal to or greater than ``ESF_SYSTEM_MANAGER_ROOT_CA_MAX_SIZE`` is specified, there will be no shortage. +
If ``0`` or ``NULL`` is specified, ``kEsfSystemManagerResultParamError`` is returned.

* *Return Value* +
+
One of the values from <<#_TableReturnValue>> is returned depending on the result.

* *Description* +
** Retrieves the Root Certificate and stores it in ``data``.  
** Execution Details  
*** Callable concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerGetRootCaRetrunValue]
.Description of return values for EsfSystemManagerGetRootCa
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
a|
* ``data == NULL``  
* ``data_size == NULL``  
* ``*data_size == 0``  
|Unchanged  
|Set the correct arguments and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|May contain undefined data.  
|Not recoverable.

|kEsfSystemManagerResultOutOfRange
|``*data_size`` is smaller than the size of the retrieved valid data.  
|May contain undefined data.  
|Specify a sufficient ``*data_size`` and retry.

|kEsfSystemManagerResultEmptyData
|Root Certificate is not stored in the ParameterStorageManager.  
|Unchanged  
|Store the correct Root Certificate.  
|===


[#_EsfSystemManagerGetRootCaHash]
==== EsfSystemManagerGetRootCaHash
* *Function* 
+
Retrieves the Root Certificate hash.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetRootCaHash( char *data, size_t *data_size )**``  

* *Arguments* +
+
**``[OUT] char *data``**:: 
Specify the starting address of the area to store the retrieved Root Certificate hash (a null-terminated string).  
**``[IN/OUT] size_t *data_size``**:: 
Specify the size of ``data``. +
The value must be ``1`` or greater, including the null-terminator. +
After this API is executed, the actual size of the retrieved valid data (including the null-terminator) is stored. +
If ``*data_size`` is smaller than the size of the valid data, ``kEsfSystemManagerResultOutOfRange`` is returned. +
If a size equal to or greater than ``ESF_SYSTEM_MANAGER_ROOT_CA_HASH_MAX_SIZE`` is specified, there will be no shortage. +
If ``0`` or ``NULL`` is specified, ``kEsfSystemManagerResultParamError`` is returned.

* *Return Value* +
+
One of the values from <<#_TableReturnValue>> is returned depending on the result.

* *Description* +
** Retrieves the Root Certificate hash and stores it in ``data``.  
** Execution Details  
*** Callable concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerGetRootCaHashReturnValue]
.Description of return values for EsfSystemManagerGetRootCaHash
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
a|
* ``data == NULL``  
* ``data_size == NULL``  
* ``*data_size == 0``  
|Unchanged  
|Set the correct arguments and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|May contain undefined data.  
|Not recoverable.

|kEsfSystemManagerResultOutOfRange
|``*data_size`` is smaller than the size of the retrieved valid data.  
|May contain undefined data.  
|Specify a sufficient ``*data_size`` and retry.

|kEsfSystemManagerResultEmptyData
|Root Certificate hash is not stored in the ParameterStorageManager.  
|Unchanged  
|Store the correct Root Certificate hash.  
|===


[#_EsfSystemManagerGetQrModeTimeoutValue]
==== EsfSystemManagerGetQrModeTimeoutValue
* *Function* 
+
Retrieves the QR mode timeout value.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetQrModeTimeoutValue( int32_t *data )**``  

* *Arguments* +
+
**``[OUT] int32_t *data``**:: 
The retrieved QR mode timeout value will be stored. The meaning of the value is not defined by the SystemManager and is left to the API user.

* *Return Value* +
+
One of the values from <<#_TableReturnValue>> is returned depending on the result.

* *Description* +
** Retrieves the QR mode timeout value and stores it in ``data``.  
** Execution Details  
*** Callable concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerGetQrModeTimeoutValueReturnValue]
.Description of return values for EsfSystemManagerGetQrModeTimeoutValue
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
|Occurs when ``data == NULL``.  
|Unchanged  
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|May contain undefined data.  
|Not recoverable.  
|===


[#_EsfSystemManagerSetQrModeTimeoutValue]
==== EsfSystemManagerSetQrModeTimeoutValue
* *Function* 
+
Saves the QR mode timeout value.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetQrModeTimeoutValue( int32_t data )**``  

* *Arguments* +
+
**``[IN] int32_t data``**:: 
QR mode timeout value. Can be specified within the range of int32_t. The meaning of the value is not defined by the SystemManager and is left to the API user.

* *Return Value* +
+
One of the values from <<#_TableReturnValue>> is returned depending on the result.

* *Description* +
** Saves the QR mode timeout value. This API only stores the value. To perform QR mode timeout operations, retrieve the value using ``EsfSystemManagerGetQrModeTimeoutValue``.  
** Execution Details  
*** Callable concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerSetQrModeTimeoutValueReturnValue]
.Description of return values for EsfSystemManagerSetQrModeTimeoutValue
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|-  
|Not recoverable.  
|===


[#_EsfSystemManagerGetInitialSettingFlag]
==== EsfSystemManagerGetInitialSettingFlag
* *Function* 
+
Retrieves the InitialSettingFlag.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetInitialSettingFlag( EsfSystemManagerInitialSettingFlag *data )**``  

* *Arguments* +
+
**``[OUT] EsfSystemManagerInitialSettingFlag *data``**:: 
The retrieved InitialSettingFlag will be stored here.

* *Return Value* +
+
One of the values from <<#_TableReturnValue>> is returned depending on the result.

* *Description* +
** Retrieves the InitialSettingFlag and stores it in ``data``.  
** Execution Details  
*** Callable concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerGetInitialSettingFlagReturnValue]
.Description of return values for EsfSystemManagerGetInitialSettingFlag
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
|Occurs when ``data == NULL``.  
|Unchanged  
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|May contain undefined data.  
|Not recoverable.

|kEsfSystemManagerResultOutOfRange
|An invalid value was retrieved from the ParameterStorageManager.  
|Unchanged  
|Write a valid value beforehand.  
|===


[#_EsfSystemManagerSetInitialSettingFlag]
==== EsfSystemManagerSetInitialSettingFlag
* *Function* 
+
Sets the InitialSettingFlag.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetInitialSettingFlag( EsfSystemManagerInitialSettingFlag data )**``  

* *Arguments* +
+
**``[IN] EsfSystemManagerInitialSettingFlag data``**:: 
The value to set for the InitialSettingFlag.

* *Return Value* +
+
One of the values from <<#_TableReturnValue>> is returned depending on the result.

* *Description* +
** Sets the InitialSettingFlag.  
** Execution Details  
*** Callable concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerSetInitialSettingFlagReturnValue]
.Description of return values for EsfSystemManagerSetInitialSettingFlag
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
|The ``data`` value contains an invalid enum.  
|-  
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|-  
|Not recoverable.  
|===


[#_EsfSystemManagerGetHwInfo]
==== EsfSystemManagerGetHwInfo
* *Function*
+
Retrieves the HW information configured on the device.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetHwInfo( EsfSystemManagerHwInfo *data )**``

* *Arguments* +
+
**``[OUT] EsfSystemManagerHwInfo *data``**::  
Specify the starting address of the area where the retrieved HW information will be stored.  
If ``NULL`` is specified, ``kEsfSystemManagerResultParamError`` is returned.

* *Return Value* +
+
One of the values from <<#_TableReturnValue>> is returned depending on the result.

* *Description* +
** Retrieves the HW information configured on the device.  
** If any member of the retrieved ``EsfSystemManagerHwInfo`` is empty, an empty string (``\0``) is returned.

** Execution Details  
*** Callable concurrently.  
*** Callable from multiple threads.  
*** Callable from multiple tasks.  
*** Performs internal blocking.  
** Error Information  
+
[#_EsfSystemManagerGetHwInfoReturnValue]
.Description of return values for EsfSystemManagerGetHwInfo
[width="100%",options="header"]
|===
|Return Value |Condition | OUT Argument Status | Recovery Method

|kEsfSystemManagerResultParamError
a|
``data == NULL``  
|Unchanged  
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the ParameterStorageManager.  
|May contain undefined data.  
|Not recoverable.

|kEsfSystemManagerResultEmptyData
|HW information is not stored on the device.  
|Unchanged  
|Properly configure HW information on the device.  
|===

[#_EsfSystemManagerGetEvpResetCause]
==== EsfSystemManagerGetEvpResetCause
* *Function* +
Retrieves the startup reason provided by EVP.

* *Format* +
``** EsfSystemManagerResult EsfSystemManagerGetEvpResetCause( EsfSystemManagerEvpResetCause *evp_reset_cause )**``  

* *Argument Description* +
**``[OUT] EsfSystemManagerEvpResetCause *evp_reset_cause``**:: 
Stores the retrieved startup reason provided by EVP.

* *Return Value* +
Returns one of the values in <<#_TableReturnValue>> according to the execution result.

* *Description* +
** Retrieves the startup reason provided by EVP and stores it in ``evp_reset_cause``.  
** If ``evp_reset_cause`` contains ``kEsfSystemManagerEvpResetCauseClear``, it indicates that no startup reason provided by EVP has been saved.  
** Execution Information
*** Can be called concurrently.  
*** Can be called from multiple threads.  
*** Can be called from multiple tasks.  
*** Blocking occurs inside the API.  
** Error Information 
+
[#_EsfSystemManagerGetEvpResetCauseReturnValue]
.Description of EsfSystemManagerGetEvpResetCause Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
|Occurs when ``evp_reset_cause == NULL``.
|Unchanged
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the Parameter Storage Manager.
|The stored value may be undefined.
|Cannot be recovered.
|===



[#_EsfSystemManagerSetEvpResetCause]
==== EsfSystemManagerSetEvpResetCause
* *Function*
+
Sets the startup reason provided by EVP.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetEvpResetCause( EsfSystemManagerEvpResetCause evp_reset_cause )**``

* *Argument Description* +
**``[IN] EsfSystemManagerEvpResetCause evp_reset_cause``**::
The startup reason provided by EVP.

* *Return Value* +
Returns one of the values in <<#_TableReturnValue>> according to the execution result.

* *Description* +
** Sets the startup reason provided by EVP.
** If ``evp_reset_cause`` is specified as ``kEsfSystemManagerEvpResetCauseClear``, deletes the saved startup reason provided by EVP.

** Execution Information
*** Can be called concurrently.
*** Can be called from multiple threads.
*** Can be called from multiple tasks.
*** Blocking occurs inside the API.
** Error Information 
+
[#_EsfSystemManagerSetEvpResetCauseReturnValue]
.Description of EsfSystemManagerSetEvpResetCause Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |Recovery Method

|kEsfSystemManagerResultParamError
a|
``evp_reset_cause >= kEsfSystemManagerEvpResetCauseMax``
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the Parameter Storage Manager.
|Cannot be recovered.

|===


[#_EsfSystemManagerGetResetCause]
==== EsfSystemManagerGetResetCause
* *Function* 
+
Retrieves the startup reason provided by the Power Manager.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerGetResetCause( EsfSystemManagerResetCause *reset_cause )**``  

* *Argument Description* +
+
**``[OUT] EsfSystemManagerResetCause *reset_cause``**:: 
Stores the retrieved startup reason provided by the Power Manager.

* *Return Value* +
+
Returns one of the values in <<#_TableReturnValue>> according to the execution result.

* *Description* +
** Retrieves the startup reason provided by the Power Manager and stores it in ``reset_cause``.
** If ``reset_cause`` contains ``kEsfSystemManagerResetCauseClear``, it indicates that no startup reason provided by the Power Manager has been saved.
** Execution Information
*** Can be called concurrently.
*** Can be called from multiple threads.
*** Can be called from multiple tasks.
*** Blocking occurs inside the API.
** Error Information
+
[#_EsfSystemManagerGetResetCauseReturnValue]
.Description of EsfSystemManagerGetResetCause Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
|Occurs when ``reset_cause == NULL``.
|Unchanged
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the Parameter Storage Manager.
|The stored value may be undefined.
|Cannot be recovered.

|===

[#_EsfSystemManagerSetResetCause]
==== EsfSystemManagerSetResetCause
* *Function*
+
Sets the startup reason provided by the Power Manager.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetResetCause( EsfSystemManagerResetCause reset_cause )**``

* *Argument Description* +
**``[IN] EsfSystemManagerResetCause reset_cause``**::
The startup reason provided by the Power Manager.

* *Return Value* +
+
Returns one of the values in <<#_TableReturnValue>> according to the execution result.

* *Description* +
** Sets the startup reason provided by the Power Manager.
** If ``reset_cause`` is specified as ``kEsfSystemManagerResetCauseClear``, deletes the saved startup reason provided by the Power Manager.

** Execution Information
*** Can be called concurrently.
*** Can be called from multiple threads.
*** Can be called from multiple tasks.
*** Blocking occurs inside the API.
** Error Information
+
[#_EsfSystemManagerSetResetCauseReturnValue]
.Description of EsfSystemManagerSetResetCause Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |Recovery Method

|kEsfSystemManagerResultParamError
a|
* ``reset_cause <= kEsfSystemManagerResetCauseUnknown``  
* ``reset_cause >= kEsfSystemManagerResetCauseMax``
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
|An error occurred in the Parameter Storage Manager.
|Cannot be recovered.

|===


[#_EsfSystemManagerSetExceptionInfo]
==== EsfSystemManagerSetExceptionInfo
* *Function*
+
Saves the startup reason and exception information.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSetExceptionInfo( void )**``

* *Argument Description* +
No arguments are specified. +

* *Return Value* +
Returns one of the values in <<#_TableReturnValue>> according to the execution result.

* *Description* +
** Based on the startup reason obtained from the Power Manager, saves the exception information and the startup reason to the Parameter Storage Manager.
** Processing flow:
*** Retrieves the startup reason from the Power Manager.
*** If the startup reason is ``kEsfPwrMgrResetCauseWDT`` or ``kEsfPwrMgrResetCauseCoreSoft``:
**** Retrieves ``ExceptionInfo`` from the Power Manager.
**** If ``ExceptionInfo`` exists, saves it to the Parameter Storage Manager.
**** Clears the ``ExceptionInfo`` in the Power Manager.
*** If ``ExceptionInfo`` does not exist:
**** If a startup reason provided by EVP is already saved, no action is taken.
**** If a startup reason has already been saved, no action is taken.
*** Determination and saving of the startup reason:
**** On the first boot, saves ``kEsfSystemManagerResetCauseSysChipPowerOnReset``.
**** If the startup reason is ``kEsfPwrMgrResetCauseSysChipPowerOnReset`` or ``kEsfPwrMgrResetCauseCoreSoft`` and ``ExceptionInfo`` is not present, it is handled as an abnormal condition.
**** Other startup reasons are converted to the appropriate value and saved.

** Execution Information
*** Can be called concurrently.
*** Can be called from multiple threads.
*** Can be called from multiple tasks.
*** Blocking occurs inside the API.
** Error Information 
+
[#_EsfSystemManagerSetExceptionInfoReturnValue]
.Description of EsfSystemManagerSetExceptionInfo Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultInternalError
a|
* An error occurred while obtaining the startup reason from the Power Manager.
* An error occurred while obtaining ``ExceptionInfo`` from the Power Manager (only on WDT startup).
* An error occurred in the Parameter Storage Manager.
* An error occurred while clearing ``ExceptionInfo`` in the Power Manager.
* An error occurred while obtaining the startup reason provided by EVP.
* An error occurred while getting or setting the startup reason.
|-
|Cannot be recovered.

|===

[#_EsfSystemManagerSendResetCause]
==== EsfSystemManagerSendResetCause
* *Function*
+
Notifies the startup reason through Elog.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerSendResetCause( void )**``

* *Argument Description* +
No arguments are specified. +

* *Return Value* +
Returns one of the values in <<#_TableReturnValue>> according to the execution result.

* *Description* +
** Retrieves from the Parameter Storage Manager the startup reason provided by EVP or by the Power Manager, and notifies it through Elog.
** Refer to <<#_DeviceResetCauseElogList>> for details of the Elog entries to be notified.
** Notification of the startup reason provided by EVP takes precedence.
** After the Elog notification is completed, the startup reason provided by EVP stored in the Parameter Storage Manager is deleted, and the startup reason provided by the Power Manager is written as ``kEsfSystemManagerResetCauseDefault``.

** Execution Information
*** Can be called concurrently.
*** Can be called from multiple threads.
*** Can be called from multiple tasks.
*** Blocking occurs inside the API.
** Error Information 
+
[#_EsfSystemManagerSendResetCauseReturnValue]
.Description of EsfSystemManagerSendResetCause Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |Recovery Method

|kEsfSystemManagerResultInternalError
|An error occurred in the Parameter Storage Manager.
|Cannot be recovered.

|===

[#_EsfSystemManagerUploadExceptionInfo]
==== EsfSystemManagerUploadExceptionInfo
* *Function*
+
Uploads exception information to the cloud via BulkDlog.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerUploadExceptionInfo( void )**``

* *Argument Description* +
No arguments are specified. +

* *Return Value* +
Returns one of the values in <<#_TableReturnValue>> according to the execution result.

* *Description* +
** Uploads exception information to the cloud via BulkDlog.
** After upload completion, the exception information stored in the Parameter Storage Manager is deleted.

** Execution Information
*** Can be called concurrently.
*** Can be called from multiple threads.
*** Can be called from multiple tasks.
*** Blocking occurs inside the API.
** Error Information 
+
[#_EsfSystemManagerUploadExceptionInfoReturnValue]
.Description of EsfSystemManagerUploadExceptionInfo Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |Recovery Method

|kEsfSystemManagerResultInternalError
|An error occurred in the Parameter Storage Manager. +
An error occurred in the Power Manager. +
An error occurred in the Log Manager.
|Cannot be recovered.

|===

[#_EsfSystemManagerIsNeedReboot]
==== EsfSystemManagerIsNeedReboot
* *Function*
+
Determines whether a system reboot is required based on the startup reason.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerIsNeedReboot( bool *reset_flag )**``

* *Argument Description* +
**``[OUT] bool *reset_flag``**::
This output pointer is used to return whether a reboot is required. +
``true``: reboot required, ``false``: reboot not required +
If ``NULL`` is specified, the function returns ``kEsfSystemManagerResultParamError`` and terminates.

* *Return Value* +
Returns one of the values in <<#_TableReturnValue>> according to the execution result.

* *Description* +
** Determines the need for a system reboot based on the startup reason obtained from the Power Manager.
** Processing flow:
*** Retrieves the startup reason from the Power Manager.
*** If the startup reason is ``kEsfPwrMgrResetCauseCoreSoft``, checks the existence of ``ExceptionInfo`` in the Parameter Storage Manager.
*** If ``ExceptionInfo`` exists, treats the startup reason as ``kEsfPwrMgrResetCauseWDT``.
*** Calls ``PlSystemManagerIsNeedReboot`` to determine whether a reboot is required.
** If ``reset_flag`` is returned as ``true``, perform a system reboot.

** Execution Information
*** Can be called concurrently.
*** Can be called from multiple threads.
*** Can be called from multiple tasks.
*** Blocking occurs inside the API.
** Error Information +
[#_EsfSystemManagerIsNeedRebootReturnValue]
.Description of EsfSystemManagerIsNeedReboot Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |State of OUT Parameter |Recovery Method

|kEsfSystemManagerResultParamError
a|
* Occurs when ``reset_flag == NULL``.
|-
|Set the correct argument and retry.

|kEsfSystemManagerResultInternalError
a|
* An error occurred while obtaining the startup reason from the Power Manager
* An error occurred in the Parameter Storage Manager
* An error occurred in the PL System Manager
|The stored value may be undefined.
|Cannot be recovered.

|===

[#_EsfSystemManagerExecReboot]
==== EsfSystemManagerExecReboot
* *Function*
+
Executes a system reboot with the specified reboot type.

* *Format* +
+
``** void EsfSystemManagerExecReboot( EsfSystemManagerRebootType reboot_type )**``

* *Argument Description* +
**``[IN] EsfSystemManagerRebootType reboot_type``**::
The reboot type to execute. Specify one of the enumeration values of ``EsfSystemManagerRebootType``.

* *Return Value* +
+
None (``void``). Since this function performs a system reboot, it does not return in the normal case.

* *Description* +
** Executes a system reboot with the specified reboot type.
** The reboot reason and processing are determined by the reboot type.
** Because this function executes a reboot, it does not return to the caller in the normal case.

** Execution Information
*** Can be called concurrently.
*** Can be called from multiple threads.
*** Can be called from multiple tasks.
*** Blocking occurs inside the API.
** Error Information
+
[#_EsfSystemManagerExecRebootReturnValue]
.Description of EsfSystemManagerExecReboot Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |Recovery Method

|No return value
|In the normal case, this function does not return because it performs a system reboot.
|Not applicable
|===


[#_EsfSystemManagerMigration]
==== EsfSystemManagerMigration
* *Function*
+
Executes the migration process for System Manager configuration data.

* *Format* +
+
``** EsfSystemManagerResult EsfSystemManagerMigration( void )**``

* *Argument Description* +
No arguments are specified. +

* *Return Value* +
Returns one of the values in <<#_TableReturnValue>> according to the execution result.

* *Description* +
** Migrates data saved in the old format to the new format.
** Sequentially migrates the following data types:
*** RootAuth : Root certificate data and its SHA-256 hash value
*** DeviceManifest : Device manifest data
*** HwInfo : Hardware information data
*** EVP Setup Info : EVP setup information
** After the migration of each data item is completed, deletes the corresponding old-format data file.
** If no target data exists, it is treated as a normal completion.
** Execution Information
*** Can be called concurrently.
*** Can be called from multiple threads.
*** Can be called from multiple tasks.
*** Blocking occurs inside the API.
** Error Information
+
[#_EsfSystemManagerMigrationReturnValue]
.Description of EsfSystemManagerMigration Return Values
[width="100%",options="header"]
|===
|Return Value |Condition |Recovery Method

|kEsfSystemManagerResultInternalError
a|
* An error occurred in the PL System Manager
* An error occurred while saving data to the Parameter Storage Manager
* Memory allocation failed
* SHA-256 hash calculation failed (RootAuth only)
|Cannot be recovered.

|===


<<<

== Example Usage of API Calls

Examples of how to invoke each API are shown below.

=== Set/Get APIs


[{mermaid_block}]
....
%%{init: {'noteAlign':'left'}}%%
sequenceDiagram
autonumber
participant App
participant SystemManager
participant ParameterStorageManager


App ->> +SystemManager: EsfSystemManagerSet〇〇〇(data)

SystemManager ->> +ParameterStorageManager: Acquire handle
ParameterStorageManager -->> -SystemManager: Handle

SystemManager ->> +ParameterStorageManager: Save data
ParameterStorageManager -->> -SystemManager: -

SystemManager ->> +ParameterStorageManager: Release handle
ParameterStorageManager -->> -SystemManager: -

SystemManager -->> -App: -


App ->> +SystemManager: EsfSystemManagerGet〇〇〇()

SystemManager ->> +ParameterStorageManager: Acquire handle
ParameterStorageManager -->> -SystemManager: Handle

SystemManager ->> +ParameterStorageManager: Retrieve data
ParameterStorageManager -->> -SystemManager: Data

SystemManager ->> +ParameterStorageManager: Release handle
ParameterStorageManager -->> -SystemManager: -

SystemManager -->> -App: Data
....

=== Device Startup Reason Notification Sequence


[{mermaid_block}]
....
sequenceDiagram
participant sc as Some Component
participant evp as EVP
participant main as EsfMain
participant SystemManager
participant PlSystemManager as PL System Manager
participant ParameterStorageManager as Parameter Storage Manager
participant PowerManager as Power Manager
participant UtilityLog as Utility Log
participant LogManager as Log Manager
autonumber

alt When restarting the system due to a normal software reset
    sc ->> +SystemManager: EsfSystemManagerExecReboot(kEsfSystemManagerRebootTypeSystemNormal)
    SystemManager ->> +ParameterStorageManager: Save startup reason
    ParameterStorageManager -->> -SystemManager: -
    SystemManager ->> -PowerManager: EsfPwrMgrExecuteRebootEx(EsfPwrMgrRebootTypeSW);
    Note over PowerManager: Return to [System Startup]

else When restarting the system due to an abnormal software reset
    sc ->> +SystemManager: EsfSystemManagerExecReboot(kEsfSystemManagerRebootTypeSystemAbnormal)
    SystemManager ->> +ParameterStorageManager: Save startup reason
    ParameterStorageManager -->> -SystemManager: -
    SystemManager ->> -PowerManager: EsfPwrMgrExecuteRebootEx(EsfPwrMgrRebootTypeHW);
    Note over PowerManager: Return to [System Startup]

else When restarting the system due to EVP
    evp ->> +SystemManager: EsfSystemManagerExecReboot(kEsfSystemManagerRebootTypeEvpMemoryAllocFailure or kEsfSystemManagerRebootTypeEvpFreezeDetection)
    SystemManager ->> +ParameterStorageManager: Save startup reason provided by EVP
    ParameterStorageManager -->> -SystemManager: -
    SystemManager ->> -PowerManager: EsfPwrMgrExecuteRebootEx(EsfPwrMgrRebootTypeHW);
    Note over PowerManager: Return to [System Startup]

else When restarting the system due to WDT
	PowerManager ->> PowerManager: System restart due to WDT
    Note over PowerManager: Return to [System Startup]
end

%%-----------------------------------------------------------------------------%%

Note over sc, LogManager: [System Startup]
Note over main: After initializing Parameter Storage Manager and Power Manager

main ->> +SystemManager: EsfSystemManagerSetExceptionInfo()

%%---Obtain startup reason from Power Manager
SystemManager ->> +PowerManager: EsfPwrMgrGetResetCause()
PowerManager -->> -SystemManager: Startup reason

alt If the startup reason is kEsfPwrMgrResetCauseWDT or kEsfPwrMgrResetCauseCoreSoft
	SystemManager ->> +PowerManager: EsfPwrMgrGetExceptionInfo()
    PowerManager -->> -SystemManager: Exception information
    
    opt If exception information exists
        SystemManager ->> +ParameterStorageManager: Save exception information
        ParameterStorageManager -->> -SystemManager: -
        SystemManager ->> +PowerManager: EsfPwrMgrClearExceptionInfo()
        PowerManager -->> -SystemManager: kEsfPwrMgrOk
        Note over SystemManager: ExceptionInfo processing completed; proceed to save the startup reason
    end
    
    opt If no exception information exists
        SystemManager ->> +ParameterStorageManager: Check whether a startup reason provided by EVP is saved
        ParameterStorageManager -->> -SystemManager: Startup reason provided by EVP
        opt If a startup reason provided by EVP is saved
            Note over SystemManager: EVP startup reason takes precedence; return to complete processing
            SystemManager -->> main: kEsfSystemManagerResultOk
        end

        SystemManager ->> +ParameterStorageManager: Check whether a startup reason is saved
        ParameterStorageManager -->> -SystemManager: Startup reason
        opt If a startup reason is saved
            SystemManager -->> main: kEsfSystemManagerResultOk
        end
    end

else For other startup reasons
    SystemManager ->> +ParameterStorageManager: Check whether a startup reason provided by EVP is saved
    ParameterStorageManager -->> -SystemManager: Startup reason provided by EVP
    opt If a startup reason provided by EVP is saved
        Note over SystemManager: EVP startup reason takes precedence; return to complete processing
        SystemManager -->> main: kEsfSystemManagerResultOk
    end

    SystemManager ->> +ParameterStorageManager: Check whether a startup reason is saved
    ParameterStorageManager -->> -SystemManager: Startup reason
    opt If a startup reason is saved
        SystemManager -->> main: kEsfSystemManagerResultOk
    end
end

SystemManager ->> +ParameterStorageManager: Save the startup reason
Note over SystemManager: If no startup reason exists (kEsfSystemManagerResetCauseClear), save kEsfSystemManagerResetCauseSysChipPowerOnReset (no startup reason exists only on first boot; treat as normal).
Note over SystemManager: If kEsfPwrMgrResetCauseSysChipPowerOnReset or kEsfPwrMgrResetCauseCoreSoft and no ExceptionInfo exists, save kEsfSystemManagerResetCauseSoftResetError (treat a reboot with no startup reason set as abnormal).
ParameterStorageManager -->> -SystemManager: -

SystemManager -->> -main: kEsfSystemManagerResultOk

%%-----------------------------------------------------------------------------%%

%%---Reboot decision
main ->> +SystemManager: EsfSystemManagerIsNeedReboot()
SystemManager ->> +PowerManager: EsfPwrMgrGetResetCause()
PowerManager -->> -SystemManager: Startup reason

alt If the startup reason is kEsfPwrMgrResetCauseCoreSoft
    SystemManager ->> +ParameterStorageManager: Check size of ExceptionInfo
    ParameterStorageManager -->> -SystemManager: Size
    opt If ExceptionInfo size > 0
        Note over SystemManager: Change the startup reason to kEsfPwrMgrResetCauseWDT
    end
end

SystemManager ->> +PlSystemManager: PlSystemManagerIsNeedReboot()
PlSystemManager -->> -SystemManager: Reboot decision (true or false) 
SystemManager -->> -main: Reboot decision (true or false) 

opt Reboot decision == true
    main ->> main: System reboot
    Note over main: Return to [System Startup]
end

%%-----------------------------------------------------------------------------%%
main ->> +SystemManager: EsfSystemManagerSendResetCause()

SystemManager ->> +ParameterStorageManager: Check whether a startup reason provided by EVP is saved
ParameterStorageManager -->> -SystemManager: Startup reason provided by EVP

alt If a startup reason provided by EVP is saved
	Note over SystemManager: Startup reason provided by EVP takes precedence
    SystemManager ->> +ParameterStorageManager: Get startup reason provided by EVP
    ParameterStorageManager -->> -SystemManager: Startup reason provided by EVP
else If a startup reason provided by EVP is not saved
    SystemManager ->> +ParameterStorageManager: Get startup reason
    ParameterStorageManager -->> -SystemManager: Startup reason
end

SystemManager ->> SystemManager: Convert the startup reason (EVP or non-EVP) to an Elog ID
SystemManager ->> +UtilityLog: WRITE_ELOG_CRITICAL(0x60XX)
UtilityLog -->> -SystemManager: -

SystemManager ->> +ParameterStorageManager: Delete startup reason provided by EVP and set startup reason to kEsfSystemManagerResetCauseDefault
ParameterStorageManager -->> -SystemManager: -
SystemManager -->> -main: kEsfSystemManagerResultOk

%%-----------------------------------------------------------------------------%%
main ->> +SystemManager: EsfSystemManagerUploadExceptionInfo()

SystemManager ->> +ParameterStorageManager: Check whether exception information is saved
ParameterStorageManager -->> -SystemManager: Size of exception information
alt If exception information is saved
  SystemManager ->> +ParameterStorageManager: Get exception information
  ParameterStorageManager -->> -SystemManager: Exception information
else If no exception information is saved
  Note over SystemManager: Normal startup; take no action and return
  SystemManager -->> main: kEsfSystemManagerResultOk
end

SystemManager ->> +PowerManager: EsfPwrMgrConvExceptionInfo(Exception information)
PowerManager -->> -SystemManager: Exception information after string conversion
SystemManager ->> +LogManager: EsfLogManagerSendBulkDlog(Exception information after string conversion)
Note over LogManager: If the destination Blob setting is written to Flash,<br>force upload even with UART settings
LogManager -->> -SystemManager: -
SystemManager ->> +ParameterStorageManager: Delete exception information
ParameterStorageManager -->> -SystemManager: kEsfParameterStorageManagerStatusOk
SystemManager -->> -main: kEsfSystemManagerResultOk

....

<<<

== Special Notes and Component-Specific Information

=== ParameterStorageManager Interface Specifications

<<<

== List of OSS Used
No OSS is used.

<<<

== References

* ParameterStorageManager Functional Specification  
** https://github.com/aitrios/aitrios-edge-device-manager/blob/main/docs/spec/esf/parameter_storage_manager/ParameterStorageManager.adoc

<<<


== Revision History
[width="100%", cols="20%,80%",options="header"]
|===
|Version |Changes 
|v0.1.0
|Initial release
|v0.1.1
a|
* Added <<#_ConfigList>>  
* Added ``kEsfSystemManagerResultOutOfRange`` and ``kEsfSystemManagerResultEmptyData``  
* Changed parameter names from ``value`` to ``data`` in <<#_EsfSystemManagerGetEvpTls>> and <<EsfSystemManagerSetEvpTls>> for consistency with other APIs  
* Added <<#_EsfSystemManagerGetEvpHubUrl>>  
* Added <<#_EsfSystemManagerGetEvpHubPort>>  
* Added <<#_EsfSystemManagerGetQrModeTimeoutValue>>  
* Added <<#_EsfSystemManagerSetQrModeTimeoutValue>>  
* Added ``size_t *data_size`` argument to <<#_EsfSystemManagerGetDeviceManifest>>, <<#_EsfSystemManagerGetProjectId>>, <<#_EsfSystemManagerGetRegisterToken>>, <<#_EsfSystemManagerGetRootCa>>, <<#_EsfSystemManagerGetTlsClientCert>>, and <<#_EsfSystemManagerGetTlsClientKey>>  
* Added ``size_t data_size`` argument to <<#_EsfSystemManagerSetProjectId>>, <<#_EsfSystemManagerSetRegisterToken>>, <<#_EsfSystemManagerSetEvpHubUrl>>, and <<#_EsfSystemManagerSetEvpHubPort>>  
* Moved "ParameterStorageManager Interface Specifications" to the SystemManager detailed design document  

|v0.1.2
a|
* Added ``kEsfSystemManagerResultOutOfRange`` as a return value for <<#_EsfSystemManagerGetEvpTls>>  
* Fixed description of ``data_size`` (was incorrectly described as a pointer) in <<#_EsfSystemManagerSetProjectId>>, <<#_EsfSystemManagerSetRegisterToken>>, <<#_EsfSystemManagerSetEvpHubUrl>>, and <<#_EsfSystemManagerSetEvpHubPort>>  

|v0.1.3
a|
* Removed EsfSystemManagerGetTlsClientCert  
* Removed EsfSystemManagerGetTlsClientKey  

|v0.1.4
a|
* Updated descriptions for EsfSystemManagerGetQrModeTimeoutValue and EsfSystemManagerSetQrModeTimeoutValue  
* Added ``kEsfSystemManagerResultMutexError``  
* Removed the note "(based on ParameterStorageManager specifications)" from the blocking behavior descriptions of each API  

|v0.1.5
a|
* Added the following to <<#_TableDataType>>:  
``ESF_SYSTEM_MANAGER_HWINFO_MODEL_NAME_MAX_SIZE``  
``ESF_SYSTEM_MANAGER_HWINFO_MANUFACTURER_NAME_MAX_SIZE``  
``ESF_SYSTEM_MANAGER_HWINFO_PRODUCT_SERIAL_NUMBER_MAX_SIZE``  
``ESF_SYSTEM_MANAGER_HWINFO_SERIAL_NUMBER_MAX_SIZE``  
``ESF_SYSTEM_MANAGER_HWINFO_AIISP_CHIP_ID_MAX_SIZE``  
``ESF_SYSTEM_MANAGER_HWINFO_SENSOR_ID_MAX_SIZE``  
``ESF_SYSTEM_MANAGER_HWINFO_APPLICATION_PROCESSOR_TYPE_MAX_SIZE``  
``ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE``  
* Added ``EsfSystemManagerGetHwInfo`` to <<#_APIList>>  
* Added anchors:  
<<#_ESF_SYSTEM_MANAGER_HWINFO_MODEL_NAME_MAX_SIZE>>  
<<#_ESF_SYSTEM_MANAGER_HWINFO_MANUFACTURER_NAME_MAX_SIZE>>  
<<#_ESF_SYSTEM_MANAGER_HWINFO_PRODUCT_SERIAL_NUMBER_MAX_SIZE>>  
<<#_ESF_SYSTEM_MANAGER_HWINFO_SERIAL_NUMBER_MAX_SIZE>>  
<<#_ESF_SYSTEM_MANAGER_HWINFO_AIISP_CHIP_ID_MAX_SIZE>>  
<<#_ESF_SYSTEM_MANAGER_HWINFO_SENSOR_ID_MAX_SIZE>>  
<<#_ESF_SYSTEM_MANAGER_HWINFO_APPLICATION_PROCESSOR_TYPE_MAX_SIZE>>  
<<#_ESF_SYSTEM_MANAGER_HWINFO_SENSOR_MODEL_NAME_MAX_SIZE>>  
* Added <<#_EsfSystemManagerGetHwInfo>>  

|v0.1.6
a|
* Configuration Additions  
** Added ``CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_INITIAL_SETTING_FLAG``  
* Data Type Additions  
** Added ``ESF_SYSTEM_MANAGER_DPS_URL_MAX_SIZE``  
** Added ``ESF_SYSTEM_MANAGER_COMMON_NAME_MAX_SIZE``  
** Added ``ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE``  
** Added ``ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE``  
** Added ``ESF_SYSTEM_MANAGER_ROOT_CA_HASH_MAX_SIZE``  
** Added ``EsfSystemManagerInitialSettingFlag``  
* API Additions  
** Added ``EsfSystemManagerGetRootCaHash``  
** Added ``EsfSystemManagerGetDpsUrl``  
** Added ``EsfSystemManagerSetDpsUrl``  
** Added ``EsfSystemManagerGetCommonName``  
** Added ``EsfSystemManagerSetCommonName``  
** Added ``EsfSystemManagerGetDpsScopeId``  
** Added ``EsfSystemManagerSetDpsScopeId``  
** Added ``EsfSystemManagerGetInitialSettingFlag``  
** Added ``EsfSystemManagerSetInitialSettingFlag``  
** Added ``EsfSystemManagerGetEvpIotPlatform``  
** Added ``EsfSystemManagerSetEvpIotPlatform``  

|v0.1.7
a|
* Updated to treat ``CONFIG_EXTERNAL_SYSTEM_MANAGER_DEFAULT_EVP_TLS`` as a string  
* Modified the meaning of EVP TLS: "0" for enabled, "1" for disabled  

|v0.1.8
a|
* Removed ``kEsfSystemManagerResultMutexError``  
* Changed sizes of the following:
** ``ESF_SYSTEM_MANAGER_DPS_SCOPE_ID_MAX_SIZE``  
** ``ESF_SYSTEM_MANAGER_PROJECT_ID_MAX_SIZE``  
** ``ESF_SYSTEM_MANAGER_REGISTER_TOKEN_MAX_SIZE``  
** ``ESF_SYSTEM_MANAGER_EVP_HUB_URL_MAX_SIZE``  
** ``ESF_SYSTEM_MANAGER_EVP_HUB_PORT_MAX_SIZE``  
** ``ESF_SYSTEM_MANAGER_IOT_PLATFORM_MAX_SIZE``  

|v0.1.9
a|
* Updated ``ESF_SYSTEM_MANAGER_HWINFO_SERIAL_NUMBER_MAX_SIZE`` to 64  

|v0.1.10
a|
* Data types added
** Added ``EsfSystemManagerResetCause``
** Added ``EsfSystemManagerEvpResetCause``
** Added ``EsfSystemManagerRebootType``

* APIs added
** Added ``EsfSystemManagerGetEvpResetCause``
** Added ``EsfSystemManagerSetEvpResetCause``
** Added ``EsfSystemManagerGetResetCause``
** Added ``EsfSystemManagerSetResetCause``
** Added ``EsfSystemManagerSetExceptionInfo``
** Added ``EsfSystemManagerSendResetCause``
** Added ``EsfSystemManagerUploadExceptionInfo``
** Added ``EsfSystemManagerIsNeedReboot``
** Added ``EsfSystemManagerExecReboot``
8
|v0.1.11
a|
** Added ``ESF_SYSTEM_MANAGER_HWINFO_DEVICE_NAME_MAX_SIZE``
** Added ``device_name`` to ``EsfSystemManagerHwInfo``
** Added ``EsfSystemManagerMigration``
** Updated the description of ``EsfSystemManagerSetExceptionInfo``
** Updated the description of ``EsfSystemManagerIsNeedReboot``

|===

