/*
* SPDX-FileCopyrightText: 2024-2025 Sony Semiconductor Solutions Corporation
*
* SPDX-License-Identifier: Apache-2.0
*/

#ifndef ESF_PARAMETER_STORAGE_MANAGER_SRC_PARAMETER_STORAGE_MANAGER_EVENT_LOG_H_
#define ESF_PARAMETER_STORAGE_MANAGER_SRC_PARAMETER_STORAGE_MANAGER_EVENT_LOG_H_

#include "parameter_storage_manager/src/parameter_storage_manager_config.h"

#ifdef CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG

#include "parameter_storage_manager/src/parameter_storage_manager_logger.h"

#define ESF_PARAMETER_STORAGE_MANAGER_COMPONENT_ID (0x8B)

#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_INVALID_PARAMETER_FAILURE (0x01)
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_INTERNAL_PROCESS_ERROR (0x02)
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_INTERNAL_PROCESS_WARN (0x52)
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_FLASH_CONTROL_FAILURE (0x03)
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_MEMORY_CONTROL_FAILURE (0x04)
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_ROLLBACK_FAILURE (0x51)
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_PORTING_LAYER_FAILURE (0x05)
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_FACTORY_RESET_ERROR (0x06)

#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_LOGIC_ERROR \
  ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID_INTERNAL_PROCESS_ERROR

#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID(event_id) \
  ((uint16_t)ESF_PARAMETER_STORAGE_MANAGER_COMPONENT_ID << 8 | (event_id))

#ifdef CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_ERROR

#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ERROR(event_id) \
  (ESF_PARAMETER_STORAGE_MANAGER_EVENT_LOGGER_ERROR(        \
      ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID(event_id)))

#endif  // CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_ERROR

#ifdef CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_WARN

#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_WARN(event_id) \
  (ESF_PARAMETER_STORAGE_MANAGER_EVENT_LOGGER_WARN(        \
      ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID(event_id)))

#endif  // CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_WARN

#ifdef CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_INFO

#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_INFO(event_id) \
  (ESF_PARAMETER_STORAGE_MANAGER_EVENT_LOGGER_INFO(        \
      ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID(event_id)))

#endif  // CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_INFO

#ifdef CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_DEBUG

#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_DEBUG(event_id) \
  (ESF_PARAMETER_STORAGE_MANAGER_EVENT_LOGGER_DEBUG(        \
      ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID(event_id)))
#endif  // CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_DEBUG

#ifdef CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_TRACE

#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_TRACE(event_id) \
  (ESF_PARAMETER_STORAGE_MANAGER_EVENT_LOGGER_TRACE(        \
      ESF_PARAMETER_STORAGE_MANAGER_EVENT_ID(event_id)))
#endif  // CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG_TRACE

#endif  // CONFIG_EXTERNAL_PARAMETER_STORAGE_MANAGER_EVENT_LOG

#ifndef ESF_PARAMETER_STORAGE_MANAGER_EVENT_ERROR
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_ERROR(event_id)
#endif
#ifndef ESF_PARAMETER_STORAGE_MANAGER_EVENT_WARN
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_WARN(event_id)
#endif
#ifndef ESF_PARAMETER_STORAGE_MANAGER_EVENT_INFO
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_INFO(event_id)
#endif
#ifndef ESF_PARAMETER_STORAGE_MANAGER_EVENT_DEBUG
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_DEBUG(event_id)
#endif
#ifndef ESF_PARAMETER_STORAGE_MANAGER_EVENT_TRACE
#define ESF_PARAMETER_STORAGE_MANAGER_EVENT_TRACE(event_id)
#endif

#endif  // ESF_PARAMETER_STORAGE_MANAGER_SRC_PARAMETER_STORAGE_MANAGER_EVENT_LOG_H_  // NOLINT
